In [1]:
import pysam

In [62]:
filepath = "/scr1/users/liuc9/mitochondrial/realdata/05-Liming/scmocha-mixed-cellline-high-depth/cromwell-executions/scMOCHA/af9a9532-a028-4f08-aed6-483d7b112e1d/call-call_mt_variants/execution/cluster/temp/ready_bam/cluster_0.qc.bam"

samfile = pysam.AlignmentFile(filepath, "rb")
tag_cj_list_0 = []
tag_cb_list_0 = []
for read in samfile.fetch("MT"):
    tag_cj_list_0.append(read.get_tag("CJ"))
    tag_cb_list_0.append(read.get_tag("CB"))
samfile.close()

In [ ]:
cluster_0 = pd.DataFrame(
    {
        "barcode": tag_cb_list_0,
        "cluster": tag_cj_list_0,
    }
)

In [67]:
cluster_0.drop_duplicates()

                  barcode    cluster
0      CATACTTCATGCAGGA-1  cluster_0
1      GTTACAGGTTGGAGAC-1  cluster_0
2      ACTTATCCACACACTA-1  cluster_0
3      TTCCTTCAGGACACTG-1  cluster_0
4      TCACACCCACAGAAGC-1  cluster_0
...                   ...        ...
23221  GTTCTATTCTTACACT-1  cluster_0
23804  AGACTCAGTATCGGTT-1  cluster_0
23862  AGACACTGTTCAGGTT-1  cluster_0
24085  CTCCCAATCATCTACT-1  cluster_0
24345  AGCGATTTCAATCCGA-1  cluster_0

[2063 rows x 2 columns]

In [4]:
samfile.check_index()

True

In [8]:
samfile = pysam.AlignmentFile(filepath, "rb")
i = 0
tag_cj_list = []
tag_pg_list = []
tag_cb_list = []
for read in samfile.fetch("MT", 0, 10000):
    # print(read.cigarstring)
    # print(read.flag)
    # print(read.get_tag("CJ"))
    # print(read.get_tag("PG"))
    # print(read.get_tag("CB"))
    # print(read)
    # i += 1
    # if i > 5:
    #     break
    tag_cj_list.append(read.get_tag("CJ"))
    tag_pg_list.append(read.get_tag("PG"))
    tag_cb_list.append(read.get_tag("CB"))
samfile.close()

In [11]:
print("CJ type:", set(tag_cj_list), ", CJ length:", len(tag_cj_list))
print("PG type:", set(tag_pg_list), ", PG length:", len(tag_pg_list))
print("CB type:", len(set(tag_cb_list)), ", CB length:", len(tag_cb_list))

CJ type: {'cluster_0'} , CJ length: 13136
PG type: {'MarkDuplicates'} , PG length: 13136
CB type: 2014 , CB length: 13136

In [34]:
filepath = "/scr1/users/liuc9/mitochondrial/realdata/05-Liming/scmocha-mixed-cellline-high-depth/cromwell-executions/scMOCHA/af9a9532-a028-4f08-aed6-483d7b112e1d/call-cell_cluster_annotation/execution/MT_cluster.bam"
samfile = pysam.AlignmentFile(filepath, "rb")
i = 0
tag_cj_list = []
tag_pg_list = []
tag_cb_list = []
for read in samfile.fetch("MT"):
    # print(read.cigarstring)
    # print(read.flag)
    # try:
    #     print(read.get_tag("CJ"))
    # except:
    #     print("NA")
    # print(read.get_tag("PG"))

    # print(read.get_tag("CB"))
    # print(read)
    # i += 1
    # if i > 5:
    #     break
    try:
        cj_tag = read.get_tag("CJ")
    except:
        cj_tag = "NA"
    try:
        cb_tag = read.get_tag("CB")
    except:
        cb_tag = "NA"
    tag_cb_list.append(cb_tag)
    tag_cj_list.append(cj_tag)
samfile.close()

In [ ]:
from collections import Counter

import pandas as pd

In [36]:
bam_barcode = pd.DataFrame({"barcode": tag_cb_list, "cluster": tag_cj_list})

In [ ]:
bam_barcode.shape, bam_barcode.dropna(subset=["barcode"]).shape, bam_barcode.dropna(
    subset=["cluster"]
).shape

((23174435, 2), (23174435, 2), (23174435, 2))

In [ ]:
bam_barcode_cluster = bam_barcode[
    (bam_barcode["cluster"] != "NA") & (bam_barcode["barcode"] != "NA")
]

In [59]:
bam_barcode_cluster.shape

(6388653, 2)

In [61]:
bam_barcode_cluster.drop_duplicates()

                     barcode    cluster
2         AGACAAAAGAGTGGCT-1  cluster_0
4         GTAGCTACAAGTTTGC-1  cluster_1
7         GGCTTGGGTTGTGTTG-1  cluster_1
10        TCGATTTTCTTCACAT-1  cluster_1
11        AACCTGAGTTGGCCGT-1  cluster_0
...                      ...        ...
10719557  TCAGCAACAATGAGCG-1  cluster_2
11794849  TGGTTAGCAAACTGCT-1  cluster_1
14914520  CTTCCGACAATCCAGT-1  cluster_2
16424223  ATTATCCGTGCGGTAA-1  cluster_0
16935523  TAACCAGAGTCCTGCG-1  cluster_2

[4347 rows x 2 columns]

In [ ]:
d = pd.read_csv(
    "/scr1/users/liuc9/mitochondrial/realdata/05-Liming/scmocha-mixed-cellline-high-depth/cromwell-executions/scMOCHA/af9a9532-a028-4f08-aed6-483d7b112e1d/call-cell_cluster_annotation/execution/barcode_cluster.tsv",
    sep="\t",
    header=None,
    names=["barcode", "tag", "cluster"],
)

In [47]:
d.shape

(4347, 3)

In [33]:
Counter(d.cluster.to_list())

Counter({'cluster_0': 2088,
         'cluster_2': 698,
         'cluster_1': 1007,
         'cluster_3': 554})