In [1]:
import sys
import gzip
import glob
import numpy as np
import pandas as pd

import matplotlib
from matplotlib import pyplot as plt

In [8]:
MGATK_OUT_DIR = "/home/liuc9/scratch/mitochondrial/PBMC_10k_v3_10x/MTbam/mgatk/final/"
sample_prefix = "mgatk"
mito_length = 16569
low_coverage_threshold = 10
mito_genome = "MT"

In [9]:
output_dir = MGATK_OUT_DIR

In [10]:
output_dir

'/home/liuc9/scratch/mitochondrial/PBMC_10k_v3_10x/MTbam/mgatk/final/'

In [11]:
glob.glob(output_dir + "*.A.txt.gz")

['/home/liuc9/scratch/mitochondrial/PBMC_10k_v3_10x/MTbam/mgatk/final/mgatk.A.txt.gz']

In [5]:
[glob.glob(output_dir + "*.{}.txt.gz".format(nt)) for nt in "ATCG"]

[[], [], [], []]

In [4]:
base_files = [glob.glob(output_dir + "*.{}.txt.gz".format(nt))[0] for nt in "ATCG"]

IndexError: list index out of range

In [37]:
base_files

['/home/liuc9/tmp/mgatk2/final/mgatk.A.txt.gz',
 '/home/liuc9/tmp/mgatk2/final/mgatk.T.txt.gz',
 '/home/liuc9/tmp/mgatk2/final/mgatk.C.txt.gz',
 '/home/liuc9/tmp/mgatk2/final/mgatk.G.txt.gz']

In [78]:
base_coverage_dict = dict()

In [79]:
i = 0
nt = "A"

In [80]:
cur_base_data = pd.read_csv(gzip.open(base_files[i]), header=None)

In [81]:
cur_base_data.head()

    0                   1   2   3
0   2  5555555555555555-1  14  15
1   5  5555555555555555-1  17  18
2   7  5555555555555555-1  19  20
3  13  5555555555555555-1  26  26
4  16  5555555555555555-1  28  29

In [82]:
fwd_base_df = cur_base_data[[0, 1, 2]].pivot_table(index=1, columns=0)

In [83]:
fwd_base_df

                                       2                                      \
0                                  2     5     6     7     13    16    18
1
0000000000000000-1                  18.0  23.0   1.0  29.0  38.0  40.0   NaN
10101010101010101010101010101010-1   4.0   4.0   NaN   5.0   5.0   6.0   NaN
1111111111111111-1                  20.0  24.0   NaN  27.0  34.0  37.0   1.0
2222222222222222-1                  17.0  19.0   NaN  23.0  32.0  36.0   NaN
3333333333333333-1                  17.0  20.0   NaN  25.0  32.0  34.0   NaN
4444444444444444-1                  15.0  19.0   0.0  22.0  27.0  29.0   NaN
5555555555555555-1                  14.0  17.0   NaN  19.0  26.0  28.0   NaN
6666666666666666-1                  12.0  16.0   NaN  17.0  23.0  24.0   NaN
7777777777777777-1                  11.0  13.0   NaN  13.0  17.0  20.0   0.0
8888888888888888-1                   5.0   5.0   NaN   5.0   5.0   5.0   NaN
9999999999999999-1                   6.0   6.0   NaN   7.0  11.0  12.0   NaN

                                                      ...                    \
0                                  21    24    25     ... 16553 16554 16555
1                                                     ...
0000000000000000-1                  45.0  48.0  49.0  ...  45.0  44.0   NaN
10101010101010101010101010101010-1   8.0   8.0   8.0  ...   9.0   9.0   NaN
1111111111111111-1                  42.0  45.0  46.0  ...  45.0  44.0   NaN
2222222222222222-1                  41.0  45.0  46.0  ...  46.0  44.0   NaN
3333333333333333-1                  40.0  43.0  44.0  ...  43.0  42.0   NaN
4444444444444444-1                  34.0  37.0  38.0  ...  41.0  40.0   NaN
5555555555555555-1                  32.0  35.0  36.0  ...  41.0  40.0   NaN
6666666666666666-1                  29.0  32.0  32.0  ...  41.0  40.0   1.0
7777777777777777-1                  20.0  22.0  22.0  ...  20.0  20.0   0.0
8888888888888888-1                   5.0   5.0   5.0  ...  17.0  17.0   NaN
9999999999999999-1                  14.0  16.0  16.0  ...  24.0  24.0   NaN


0                                  16556 16557 16559 16561 16564 16566 16567
1
0000000000000000-1                  42.0  41.0  39.0  37.0  34.0   NaN  31.0
10101010101010101010101010101010-1   8.0   7.0   6.0   6.0   5.0   NaN   5.0
1111111111111111-1                  41.0  40.0  38.0  37.0  35.0   NaN  32.0
2222222222222222-1                  42.0  41.0  39.0  37.0  34.0   NaN  31.0
3333333333333333-1                  40.0  39.0  37.0  35.0  32.0   0.0  29.0
4444444444444444-1                  39.0  38.0  36.0  34.0  31.0   NaN  28.0
5555555555555555-1                  38.0  37.0  35.0  33.0  30.0   NaN  27.0
6666666666666666-1                  39.0  38.0  36.0  34.0  31.0   NaN  28.0
7777777777777777-1                  18.0  18.0  18.0  18.0  16.0   NaN  15.0
8888888888888888-1                  16.0  16.0  16.0  16.0  14.0   NaN  13.0
9999999999999999-1                  22.0  22.0  20.0  20.0  18.0   NaN  17.0

[11 rows x 8669 columns]

In [88]:
fwd_base_df.columns = [x[1] for x in fwd_base_df.columns.values]

In [89]:
fwd_base_df.index.name = None

In [90]:
fwd_base_df.head()

,2,5,6,7,13,16,18,21,24,25,...,16553,16554,16555,16556,16557,16559,16561,16564,16566,16567
0000000000000000-1,18.0,23.0,1.0,29.0,38.0,40.0,NaN,45.0,48.0,49.0,...,45.0,44.0,NaN,42.0,41.0,39.0,37.0,34.0,NaN,31.0
10101010101010101010101010101010-1,4.0,4.0,NaN,5.0,5.0,6.0,NaN,8.0,8.0,8.0,...,9.0,9.0,NaN,8.0,7.0,6.0,6.0,5.0,NaN,5.0
1111111111111111-1,20.0,24.0,NaN,27.0,34.0,37.0,1.0,42.0,45.0,46.0,...,45.0,44.0,NaN,41.0,40.0,38.0,37.0,35.0,NaN,32.0
2222222222222222-1,17.0,19.0,NaN,23.0,32.0,36.0,NaN,41.0,45.0,46.0,...,46.0,44.0,NaN,42.0,41.0,39.0,37.0,34.0,NaN,31.0
3333333333333333-1,17.0,20.0,NaN,25.0,32.0,34.0,NaN,40.0,43.0,44.0,...,43.0,42.0,NaN,40.0,39.0,37.0,35.0,32.0,0.0,29.0

In [97]:
all_columns = [x for x in range(1, mito_length + 1)]

In [99]:
fwd_base_df = fwd_base_df.reindex(columns=all_columns, fill_value=0)

In [94]:
missing_pos = [x for x in range(1, mito_length + 1) if x not in fwd_base_df.columns]

In [70]:
fwd_base_df[missing_pos] = 0

KeyError: "None of [Int64Index([    1,     3,     4,     8,     9,    10,    11,    12,    14,\n               15,\n            ...\n            16548, 16549, 16550, 16558, 16560, 16562, 16563, 16565, 16568,\n            16569],\n           dtype='int64', length=7900)] are in the [columns]"

In [71]:
fwd_base_df.head()

,2,5,6,7,13,16,18,21,24,25,...,16548,16549,16550,16558,16560,16562,16563,16565,16568,16569
0000000000000000-1,18.0,23.0,1.0,29.0,38.0,40.0,NaN,45.0,48.0,49.0,...,0,0,0,0,0,0,0,0,0,0
10101010101010101010101010101010-1,4.0,4.0,NaN,5.0,5.0,6.0,NaN,8.0,8.0,8.0,...,0,0,0,0,0,0,0,0,0,0
1111111111111111-1,20.0,24.0,NaN,27.0,34.0,37.0,1.0,42.0,45.0,46.0,...,0,0,0,0,0,0,0,0,0,0
2222222222222222-1,17.0,19.0,NaN,23.0,32.0,36.0,NaN,41.0,45.0,46.0,...,0,0,0,0,0,0,0,0,0,0
3333333333333333-1,17.0,20.0,NaN,25.0,32.0,34.0,NaN,40.0,43.0,44.0,...,0,0,0,0,0,0,0,0,0,0

In [72]:
 fwd_base_df = fwd_base_df.fillna(0).sort_index(axis=1)

In [73]:
fwd_base_df.head()

,1,2,3,4,5,6,7,8,9,10,...,16560,16561,16562,16563,16564,16565,16566,16567,16568,16569
0000000000000000-1,0,18.0,0,0,23.0,1.0,29.0,0,0,0,...,0,37.0,0,0,34.0,0,0.0,31.0,0,0
10101010101010101010101010101010-1,0,4.0,0,0,4.0,0.0,5.0,0,0,0,...,0,6.0,0,0,5.0,0,0.0,5.0,0,0
1111111111111111-1,0,20.0,0,0,24.0,0.0,27.0,0,0,0,...,0,37.0,0,0,35.0,0,0.0,32.0,0,0
2222222222222222-1,0,17.0,0,0,19.0,0.0,23.0,0,0,0,...,0,37.0,0,0,34.0,0,0.0,31.0,0,0
3333333333333333-1,0,17.0,0,0,20.0,0.0,25.0,0,0,0,...,0,35.0,0,0,32.0,0,0.0,29.0,0,0

In [74]:
rev_base_df = cur_base_data[[0, 1, 3]].pivot_table(index=1, columns=0)
rev_base_df.columns = [x[1] for x in rev_base_df.columns.values]
rev_base_df.index.name = None
missing_pos = [x for x in range(1, mito_length + 1) if x not in rev_base_df.columns]
rev_base_df[missing_pos] = 0
rev_base_df = rev_base_df.fillna(0).sort_index(axis=1)

/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0
/tmp/ipykernel_1719919/148629758.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rev_base_df[missing_pos] = 0