In [1]:
!hostname

c-11-03

In [2]:
import sys
import gzip
import glob
import numpy as np
import pandas as pd

import matplotlib
from matplotlib import pyplot as plt

In [3]:
def load_mgatk_output(output_dir, mito_length):
    # assuming mgatk output naming convention
    base_files = [glob.glob(output_dir + "*.{}.txt.gz".format(nt))[0] for nt in "ATCG"]

    base_coverage_dict = dict()
    for i, nt in enumerate("ATCG"):
        cur_base_data = pd.read_csv(gzip.open(base_files[i]), header=None)

        # gather coverage for forward strand
        fwd_base_df = cur_base_data[[0, 1, 2]].pivot_table(index=1, columns=0)
        fwd_base_df.columns = [x[1] for x in fwd_base_df.columns.values]  # flatten weird multiindex after pivot
        fwd_base_df.index.name = None
        # missing_pos = [x for x in range(1, mito_length + 1) if x not in fwd_base_df.columns]
        # fwd_base_df[missing_pos] = 0  # fill in missing positions
        all_columns = [x for x in range(1, mito_length + 1)]
        fwd_base_df = fwd_base_df.reindex(columns=all_columns, fill_value=0)
        fwd_base_df = fwd_base_df.fillna(0).sort_index(axis=1)  # assume all nan are true zeroes

        # gather coverage for forward strand
        rev_base_df = cur_base_data[[0, 1, 3]].pivot_table(index=1, columns=0)
        rev_base_df.columns = [x[1] for x in rev_base_df.columns.values]
        rev_base_df.index.name = None
        # missing_pos = [x for x in range(1, mito_length + 1) if x not in rev_base_df.columns]
        # rev_base_df[missing_pos] = 0
        all_columns = [x for x in range(1, mito_length + 1)]
        rev_base_df = rev_base_df.reindex(columns=all_columns, fill_value=0)
        rev_base_df = rev_base_df.fillna(0).sort_index(axis=1)

        # organize base data into a dict
        base_coverage_dict[nt] = (fwd_base_df, rev_base_df)

    return base_coverage_dict


def gather_possible_variants(base_coverage_dict, reference_file):
    # sum across cells and strands for each base and position
    aggregated_genotype = pd.DataFrame(np.zeros((4, mito_length)), index=list("ATCG"), columns=np.arange(1, mito_length + 1))
    for nt in base_coverage_dict:
        # sum across cells for each strand separately
        fwd_base_df, rev_base_df = base_coverage_dict[nt]
        fwd_base_sum, rev_base_sum = fwd_base_df.sum(), rev_base_df.sum()

        # sequencing artifact if a base/position is only nonzero for one strand across cells, ignore them
        masking = ~((fwd_base_sum > 0) & (rev_base_sum > 0))  # True if position not >0 for both strands
        fwd_base_sum[masking], rev_base_sum[masking] = 0, 0

        # sum across strands
        aggregated_genotype.loc[nt, :] = fwd_base_sum + rev_base_sum

    # make a reference set of tuples (pos, ref_base)
    ref_set = [x.strip().split() for x in open(reference_file, "r").readlines()]
    ref_N_positions = [int(x[0]) for x in ref_set if x[1].upper() not in letters]
    ref_set = set([(int(x[0]), x[1].upper()) for x in ref_set if x[1].upper() in letters])
    ref_dict = dict(ref_set)

    # make an observed set of tuples which are nonzero
    non_zero_idx = np.where(aggregated_genotype > 0)
    non_zero_bases = [letters[i] for i in non_zero_idx[0]]
    non_zero_pos = [int(i + 1) for i in non_zero_idx[1]]
    observed_set = list(zip(non_zero_pos, non_zero_bases))
    observed_set = set([x for x in observed_set if x[0] not in ref_N_positions])  # disregard positions in ref with N

    # take difference between observed and reference
    variant_set = observed_set - ref_set
    variants = sorted([(x[0], ref_dict[x[0]], x[1]) for x in list(variant_set)], key=lambda x: x[0])  # (pos, ref base, obs base)

    return variants

In [4]:
# MGATK_OUT_DIR = sys.argv[1]
MGATK_OUT_DIR = "/home/liuc9/github/scMOCHA/05-Liming/scmocha-mixed-cellline-high-depth2/cromwell-executions/scMOCHA/139358d8-df39-4274-b931-9c42b8d9c3bb/call-call_mt_variants/execution/cluster/final/"
# sample_prefix = sys.argv[2]
sample_prefix = "cluster"
# mito_length = int(sys.argv[3])  # 16569
mito_length = 16569
# low_coverage_threshold = int(sys.argv[4])  # 10
low_coverage_threshold = 10
# mito_genome = sys.argv[5]  # chrM
mito_genome = "MT"

In [15]:
letters = list("ATCG")

base_coverage_dict = load_mgatk_output(MGATK_OUT_DIR, mito_length)
cell_barcodes = base_coverage_dict["A"][0].index

In [22]:
# total coverage per position per cell
total_coverage = pd.DataFrame(np.zeros((len(cell_barcodes), mito_length)), index=cell_barcodes, columns=np.arange(1, mito_length + 1))

In [23]:
total_coverage

,1,2,3,4,5,6,7,8,9,10,...,16560,16561,16562,16563,16564,16565,16566,16567,16568,16569
cluster_0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cluster_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cluster_2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cluster_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cluster_4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
for nt in base_coverage_dict:
    total_coverage += base_coverage_dict[nt][0]
    total_coverage += base_coverage_dict[nt][1]

In [35]:
total_coverage.iloc[:, 6775]

cluster_0    20.0
cluster_1     0.0
cluster_2     9.0
cluster_3     8.0
cluster_4     8.0
Name: 6776, dtype: float64

In [36]:
# exclude low coverage cells from variant calling
cell_barcodes = total_coverage.index[total_coverage.mean(axis=1) > low_coverage_threshold]

In [39]:

for nt in base_coverage_dict:
    base_coverage_dict[nt] = (base_coverage_dict[nt][0].loc[cell_barcodes, :], base_coverage_dict[nt][1].loc[cell_barcodes, :])
total_coverage = total_coverage.loc[cell_barcodes, :]

In [40]:
base_coverage_dict

{'A': (           1      2      3      4      5      6      7      8      9      \
  cluster_0      0   28.0      0      0   31.0      0   37.0      0    0.0
  cluster_1      0    8.0      0      0    9.0      0   11.0      0    0.0
  cluster_2      0   15.0      0      0   17.0      0   20.0      0    0.0
  cluster_3      0   19.0      0      0   24.0      0   26.0      0    0.0
  cluster_4      0   15.0      0      0   18.0      0   20.0      0    0.0

             10     ...  16560  16561  16562  16563  16564  16565  16566  16567  \
  cluster_0    0.0  ...      0   40.0      0      0   37.0      0      0   33.0
  cluster_1    0.0  ...      0   22.0      0      0   20.0      0      0   18.0
  cluster_2    0.0  ...      0   41.0      0      0   38.0      0      0   35.0
  cluster_3    0.0  ...      0   39.0      0      0   36.0      0      0   33.0
  cluster_4    0.0  ...      0   38.0      0      0   35.0      0      0   32.0

             16568  16569
  cluster_0      0      0
  cluster_1      0      0
  cluster_2      0      0
  cluster_3      0      0
  cluster_4      0      0

  [5 rows x 16569 columns],
             1      2      3      4      5      6      7      8      9      \
  cluster_0      0   32.0      0      0   36.0      0   38.0      0    0.0
  cluster_1      0   12.0      0      0   14.0      0   16.0      0    0.0
  cluster_2      0   15.0      0      0   18.0      0   20.0      0    1.0
  cluster_3      0   15.0      0      0   18.0      0   21.0      0    0.0
  cluster_4      0   18.0      0      0   21.0      0   23.0      0    0.0

             10     ...  16560  16561  16562  16563  16564  16565  16566  16567  \
  cluster_0    0.0  ...      0   51.0      0      0   48.0      0      0   45.0
  cluster_1    0.0  ...      0   25.0      0      0   25.0      0      0   23.0
  cluster_2    0.0  ...      0   36.0      0      0   33.0      0      0   30.0
  cluster_3    1.0  ...      0   43.0      0      0   40.0      0      0   37.0
  cluster_4    0.0  ...      0   40.0      0      0   37.0      0      0   34.0

             16568  16569
  cluster_0      0      0
  cluster_1      0      0
  cluster_2      0      0
  cluster_3      0      0
  cluster_4      0      0

  [5 rows x 16569 columns]),
 'T': (           1      2      3      4      5      6      7      8      9      \
  cluster_0      0      0   29.0      0      0      0      0      0      0
  cluster_1      0      0    8.0      0      0      0      0      0      0
  cluster_2      0      0   16.0      0      0      0      0      0      0
  cluster_3      0      0   21.0      0      0      0      0      0      0
  cluster_4      0      0   16.0      0      0      0      0      0      0

             10     ...  16560  16561  16562  16563  16564  16565  16566  16567  \
  cluster_0   43.0  ...      0      0   39.0      0      0      0      0      0
  cluster_1   13.0  ...      0      0   21.0      0      0      0      0      0
  cluster_2   25.0  ...      0      0   40.0      0      0      0      0      0
  cluster_3   29.0  ...      0      0   38.0      0      0      0      0      0
  cluster_4   23.0  ...      0      0   37.0      0      0      0      0      0

             16568  16569
  cluster_0   32.0      0
  cluster_1   17.0      0
  cluster_2   34.0      0
  cluster_3   32.0      0
  cluster_4   31.0      0

  [5 rows x 16569 columns],
             1      2      3      4      5      6      7      8      9      \
  cluster_0      0      0   34.0      0      0      0      0      0      0
  cluster_1      0      0   12.0      0      0      0      0      0      0
  cluster_2      0      0   16.0      0      0      0      0      0      0
  cluster_3      0      0   17.0      0      0      0      0      0      0
  cluster_4      0      0   19.0      0      0      0      0      0      0

             10     ...  16560  16561  16562  16563  16564  16565  16566  16567  \
  cluster_0   41.0  ...      0      0   50.0      0      0      0      0      0
  cluster_1   18.0  ...      0      0   25.0      0      0      0      0      0
  cluster_2   23.0  ...      0      0   35.0      0      0      0      0      0
  cluster_3   23.0  ...      0      0   42.0      0      0      0      0      0
  cluster_4   26.0  ...      0      0   39.0      0      0      0      0      0

             16568  16569
  cluster_0   44.0      0
  cluster_1   23.0      0
  cluster_2   30.0      0
  cluster_3   36.0      0
  cluster_4   33.0      0

  [5 rows x 16569 columns]),
 'C': (           1      2      3      4      5      6      7      8      9      \
  cluster_0      0      0    0.0   30.0      0   33.0      0      0    0.0
  cluster_1      0      0    0.0    9.0      0   10.0      0      0    0.0
  cluster_2      0      0    0.0   17.0      0   19.0      0      0    0.0
  cluster_3      0      0    0.0   23.0      0   25.0      0      0    0.0
  cluster_4      0      0    0.0   17.0      0   19.0      0      0    0.0

             10     ...  16560  16561  16562  16563  16564  16565  16566  16567  \
  cluster_0      0  ...   41.0      0      0   38.0      0   36.0      0      0
  cluster_1      0  ...   22.0      0      0   20.0      0   20.0      0      0
  cluster_2      0  ...   42.0      0      0   39.0      0   37.0      0      0
  cluster_3      0  ...   40.0      0      0   37.0      0   35.0      0      0
  cluster_4      0  ...   39.0      0      0   36.0      0   34.0      0      0

             16568  16569
  cluster_0      0      0
  cluster_1      0      0
  cluster_2      0      0
  cluster_3      0      0
  cluster_4      0      0

  [5 rows x 16569 columns],
             1      2      3      4      5      6      7      8      9      \
  cluster_0      0      0    0.0   35.0      0   37.0      0      0    0.0
  cluster_1      0      0    1.0   13.0      0   15.0      0      0    1.0
  cluster_2      0      0    0.0   17.0      0   19.0      0      0    0.0
  cluster_3      0      0    0.0   17.0      0   20.0      0      0    0.0
  cluster_4      0      0    0.0   20.0      0   22.0      0      0    0.0

             10     ...  16560  16561  16562  16563  16564  16565  16566  16567  \
  cluster_0      0  ...   52.0      0      0   49.0      0   47.0      0      0
  cluster_1      0  ...   26.0      0      0   25.0      0   24.0      0      0
  cluster_2      0  ...   37.0      0      0   34.0      0   32.0      0      0
  cluster_3      0  ...   44.0      0      0   41.0      0   39.0      0      0
  cluster_4      0  ...   41.0      0      0   38.0      0   36.0      0      0

             16568  16569
  cluster_0      0      0
  cluster_1      0      0
  cluster_2      0      0
  cluster_3      0      0
  cluster_4      0      0

  [5 rows x 16569 columns]),
 'G': (           1      2      3      4      5      6      7      8      9      \
  cluster_0   27.0      0      0      0      0      0      0   39.0   40.0
  cluster_1    7.0      0      0      0      0      0      0   12.0   12.0
  cluster_2   13.0      0      0      0      0      0      0   21.0   22.0
  cluster_3   18.0      0      0      0      0      0      0   27.0   28.0
  cluster_4   14.0      0      0      0      0      0      0   21.0   22.0

             10     ...  16560  16561  16562  16563  16564  16565  16566  16567  \
  cluster_0      0  ...      0      0      0      0      0      0   35.0      0
  cluster_1      0  ...      0      0      0      0      0      0   19.0      0
  cluster_2      0  ...      0      0      0      0      0      0   36.0      0
  cluster_3      0  ...      0      0      0      0      0      0   34.0      0
  cluster_4      0  ...      0      0      0      0      0      0   33.0      0

             16568  16569
  cluster_0      0   31.0
  cluster_1      0   17.0
  cluster_2      0   33.0
  cluster_3      0   31.0
  cluster_4      0   30.0

  [5 rows x 16569 columns],
             1      2      3      4      5      6      7      8      9      \
  cluster_0   30.0      0      0      0      0      0      0   39.0   40.0
  cluster_1   11.0      0      0      0      0      0      0   16.0   16.0
  cluster_2   13.0      0      0      0      0      0      0   21.0   21.0
  cluster_3   14.0      0      0      0      0      0      0   22.0   23.0
  cluster_4   16.0      0      0      0      0      0      0   24.0   25.0

             10     ...  16560  16561  16562  16563  16564  16565  16566  16567  \
  cluster_0      0  ...      0      0      0      0      0      0   46.0      0
  cluster_1      0  ...      0      0      0      0      0      0   23.0      0
  cluster_2      0  ...      0      0      0      0      0      0   31.0      0
  cluster_3      0  ...      0      0      0      0      0      0   38.0      0
  cluster_4      0  ...      0      0      0      0      0      0   35.0      0

             16568  16569
  cluster_0      0   43.0
  cluster_1      0   22.0
  cluster_2      0   29.0
  cluster_3      0   35.0
  cluster_4      0   32.0

  [5 rows x 16569 columns])}

In [41]:
# call potential variants
variants = gather_possible_variants(base_coverage_dict, MGATK_OUT_DIR + mito_genome + "_refAllele.txt")

variant_names = ["{}{}>{}".format(x[0], x[1], x[2]) for x in variants]

In [43]:
variant_names

['58T>C',
 '64C>T',
 '72T>A',
 '73A>G',
 '146T>C',
 '152T>C',
 '195T>C',
 '198C>T',
 '225G>T',
 '226T>C',
 '263A>G',
 '282T>A',
 '292T>A',
 '293T>C',
 '295C>T',
 '295C>G',
 '299C>A',
 '302A>C',
 '303C>T',
 '303C>A',
 '304C>A',
 '305C>T',
 '308C>T',
 '309C>T',
 '310T>C',
 '311C>T',
 '312C>T',
 '315C>T',
 '316G>C',
 '342T>A',
 '356C>A',
 '357A>C',
 '380G>A',
 '410G>C',
 '447C>G',
 '592C>T',
 '658G>T',
 '731A>G',
 '750A>G',
 '769G>A',
 '775C>T',
 '887G>A',
 '916C>T',
 '929A>G',
 '933G>A',
 '961T>A',
 '1018G>A',
 '1042T>C',
 '1438A>G',
 '1465C>A',
 '1598G>C',
 '1602C>A',
 '1604G>A',
 '1768G>T',
 '1770G>A',
 '1784A>G',
 '1883G>A',
 '1894G>T',
 '1949G>A',
 '1987G>A',
 '2071T>A',
 '2149G>A',
 '2157T>A',
 '2212C>T',
 '2240C>A',
 '2262C>T',
 '2330T>A',
 '2408T>C',
 '2416T>C',
 '2469A>G',
 '2535A>G',
 '2617A>C',
 '2617A>G',
 '2617A>T',
 '2706A>G',
 '2789C>T',
 '2809C>T',
 '2838A>G',
 '2846G>A',
 '2871T>C',
 '3000A>G',
 '3010G>A',
 '3072T>C',
 '3076A>G',
 '3097T>C',
 '3109T>C',
 '3110C>A',
 '3197T>C',
 '3243A>G',
 '3254C>T',
 '3344T>A',
 '3345T>C',
 '3380G>A',
 '3427G>T',
 '3462C>T',
 '3487C>G',
 '3519C>T',
 '3530C>T',
 '3535T>C',
 '3541C>T',
 '3567C>A',
 '3579A>T',
 '3592G>A',
 '3594C>T',
 '3599T>C',
 '3619A>T',
 '3625G>T',
 '3625G>A',
 '3635G>C',
 '3643G>C',
 '3689C>T',
 '3696C>A',
 '3732T>A',
 '3791T>A',
 '3814G>T',
 '3829C>T',
 '3874C>T',
 '3922G>A',
 '3931T>C',
 '3992C>T',
 '4024A>G',
 '4034T>C',
 '4408G>A',
 '4429G>A',
 '4440G>A',
 '4444A>T',
 '4729C>A',
 '4747A>C',
 '4769A>T',
 '4769A>C',
 '4769A>G',
 '4826C>T',
 '4836C>T',
 '4860C>T',
 '4928T>C',
 '4931C>G',
 '4992C>T',
 '5004T>C',
 '5027C>T',
 '5112G>A',
 '5174C>T',
 '5227G>A',
 '5295C>T',
 '5339C>T',
 '5424C>T',
 '5436A>C',
 '5474A>T',
 '5481C>T',
 '5533A>T',
 '5541C>T',
 '5579G>C',
 '5581A>G',
 '5605A>T',
 '5611C>A',
 '5746G>A',
 '5798C>T',
 '5852T>A',
 '6063T>C',
 '6354C>T',
 '6415T>A',
 '6443A>C',
 '6445C>T',
 '6463C>T',
 '6655T>A',
 '6661T>C',
 '6669C>T',
 '6685A>C',
 '6687T>C',
 '6691G>A',
 '6722G>A',
 '6723G>A',
 '6776T>C',
 '7028C>T',
 '7123A>T',
 '7143T>C',
 '7175T>C',
 '7204C>T',
 '7235C>T',
 '7253A>T',
 '7256C>T',
 '7274C>T',
 '7328C>T',
 '7332G>A',
 '7335T>A',
 '7365C>A',
 '7472A>C',
 '7473A>T',
 '7516A>C',
 '7517A>C',
 '7526A>G',
 '7598G>A',
 '7601C>G',
 '7655C>T',
 '7664G>C',
 '7707C>T',
 '7765A>G',
 '7771A>G',
 '7771A>C',
 '7803T>C',
 '7830G>T',
 '7830G>A',
 '7831C>T',
 '7835C>T',
 '7880T>C',
 '7887G>T',
 '7901T>C',
 '7926G>A',
 '7985C>T',
 '7999T>C',
 '8060G>A',
 '8066C>T',
 '8134T>C',
 '8206G>A',
 '8269G>A',
 '8384A>T',
 '8387G>A',
 '8465C>A',
 '8480C>T',
 '8505A>G',
 '8513C>A',
 '8555T>A',
 '8562C>A',
 '8701A>G',
 '8783G>C',
 '8860A>T',
 '8860A>G',
 '8881T>A',
 '8908T>A',
 '8909T>C',
 '8937T>C',
 '8969G>A',
 '9071C>T',
 '9123G>A',
 '9136A>T',
 '9153C>G',
 '9221A>G',
 '9334T>C',
 '9358C>A',
 '9430T>C',
 '9441C>T',
 '9477G>T',
 '9477G>A',
 '9537C>T',
 '9540T>C',
 '9543G>A',
 '9617A>G',
 '9811G>C',
 '9853C>T',
 '9856T>C',
 '9916C>T',
 '9999A>T',
 '10014G>T',
 '10044A>G',
 '10115T>C',
 '10229A>G',
 '10396G>A',
 '10398A>G',
 '10413A>T',
 '10414G>A',
 '10473C>T',
 '10474C>A',
 '10546T>A',
 '10560C>G',
 '10564G>T',
 '10565C>T',
 '10606T>C',
 '10625C>T',
 '10668G>A',
 '10727C>G',
 '10745C>T',
 '10820C>A',
 '10840A>G',
 '10873T>C',
 '10885T>A',
 '10953T>A',
 '10971G>A',
 '10993G>T',
 '10994G>C',
 '11054C>A',
 '11071C>G',
 '11122C>A',
 '11146C>T',
 '11203C>T',
 '11228T>C',
 '11423G>A',
 '11467A>G',
 '11477G>A',
 '11478G>A',
 '11509C>G',
 '11534T>C',
 '11691G>A',
 '11693G>C',
 '11716C>T',
 '11719G>A',
 '11722T>C',
 '11743C>T',
 '11799G>A',
 '11818A>T',
 '11861G>C',
 '11914G>A',
 '11944T>C',
 '11947A>G',
 '12011T>C',
 '12045C>T',
 '12066T>C',
 '12096T>C',
 '12136T>G',
 '12138G>A',
 '12139T>A',
 '12146A>G',
 '12168G>C',
 '12169T>A',
 '12170G>C',
 '12226G>C',
 '12242A>G',
 '12308A>G',
 '12345G>A',
 '12346C>T',
 '12372G>A',
 '12388C>T',
 '12390C>T',
 '12401C>A',
 '12418A>G',
 '12456C>T',
 '12545C>T',
 '12662A>T',
 '12669C>A',
 '12693A>G',
 '12705C>T',
 '12705C>A',
 '12772G>A',
 '12779G>A',
 '12801C>T',
 '12869G>A',
 '12923G>A',
 '12948A>G',
 '13022T>C',
 '13105A>G',
 '13172G>C',
 '13180G>A',
 '13201G>C',
 '13211C>T',
 '13261C>T',
 '13394A>G',
 '13415G>T',
 '13426A>G',
 '13444T>A',
 '13474T>A',
 '13481G>C',
 '13493T>C',
 '13559C>G',
 '13572T>C',
 '13590G>A',
 '13594A>G',
 '13617T>C',
 '13646T>A',
 '13650C>T',
 '13651A>C',
 '13683C>T',
 '13688T>C',
 '13705C>T',
 '13709C>T',
 '13710A>T',
 '13710A>C',
 '13710A>G',
 '13730G>A',
 '13760C>T',
 '13769T>C',
 '13801A>G',
 '13803A>G',
 '13804G>C',
 '13810G>C',
 '13843G>T',
 '13853A>G',
 '13889G>A',
 '13923C>T',
 '13977C>A',
 '14148A>G',
 '14214C>A',
 '14249G>A',
 '14338C>T',
 '14350C>A',
 '14365C>T',
 '14400C>T',
 '14407C>A',
 '14410G>A',
 '14429C>T',
 '14433C>A',
 '14437A>G',
 '14454C>G',
 '14462G>C',
 '14480A>G',
 '14502T>A',
 '14503T>C',
 '14503T>A',
 '14504A>T',
 '14528C>G',
 '14531C>A',
 '14533C>A',
 '14535C>A',
 '14550T>A',
 '14559C>A',
 '14566A>G',
 '14582A>G',
 '14622C>T',
 '14623C>A',
 '14685G>A',
 '14766C>T',
 '14793A>G',
 '14806C>T',
 '14820C>T',
 '14859G>A',
 '14875C>T',
 '14973G>A',
 '15008T>A',
 '15045G>A',
 '15063C>T',
 '15141T>C',
 '15162C>T',
 '15180T>A',
 '15218A>G',
 '15259C>T',
 '15300T>C',
 '15301G>A',
 '15304C>T',
 '15307C>T',
 '15326A>G',
 '15339T>C',
 '15431G>A',
 '15455C>T',
 '15466G>A',
 '15483C>T',
 '15516C>T',
 '15530T>C',
 '15784T>C',
 '15855C>T',
 '15883G>A',
 '15927G>A',
 '15943T>C',
 '16072C>T',
 '16075T>A',
 '16146A>T',
 '16166A>T',
 '16168C>A',
 '16184C>A',
 '16189T>C',
 '16192C>T',
 '16209T>C',
 '16223C>T',
 '16255G>C',
 '16256C>T',
 '16270C>T',
 '16278C>T',
 '16294C>T',
 '16309A>G',
 '16366C>T',
 '16390G>A',
 '16399A>G',
 '16519T>C']

In [50]:
variants[:5], variant_names[:5]

([(58, 'T', 'C'),
  (64, 'C', 'T'),
  (72, 'T', 'A'),
  (73, 'A', 'G'),
  (146, 'T', 'C')],
 ['58T>C', '64C>T', '72T>A', '73A>G', '146T>C'])

In [51]:
total_coverage[6776]

cluster_0    20.0
cluster_1     0.0
cluster_2     9.0
cluster_3     8.0
cluster_4     8.0
Name: 6776, dtype: float64

In [44]:
# build two <cell by variant tables>, one for each strand
total_coverage_variant_df = []
fwd_cell_variant_df, rev_cell_variant_df = [], []
for i, var in enumerate(variants):
    var_name = variant_names[i]
    pos, base = var[0], var[2]
    total_coverage_variant_df.append(total_coverage[pos])
    fwd_cell_variant_df.append(base_coverage_dict[base][0][pos].values)
    rev_cell_variant_df.append(base_coverage_dict[base][1][pos].values)
total_coverage_variant_df = pd.DataFrame(np.array(total_coverage_variant_df).T, index=cell_barcodes, columns=variant_names)
fwd_cell_variant_df = pd.DataFrame(np.array(fwd_cell_variant_df).T, index=cell_barcodes, columns=variant_names)
rev_cell_variant_df = pd.DataFrame(np.array(rev_cell_variant_df).T, index=cell_barcodes, columns=variant_names)
all_cell_variant_df = fwd_cell_variant_df + rev_cell_variant_df

In [52]:
total_coverage_variant_df["6776T>C"]

cluster_0    20.0
cluster_1     0.0
cluster_2     9.0
cluster_3     8.0
cluster_4     8.0
Name: 6776T>C, dtype: float64

In [53]:
fwd_cell_variant_df["6776T>C"]

cluster_0    17.0
cluster_1     0.0
cluster_2     0.0
cluster_3     0.0
cluster_4     0.0
Name: 6776T>C, dtype: float64

In [54]:
rev_cell_variant_df["6776T>C"]

cluster_0    1.0
cluster_1    0.0
cluster_2    0.0
cluster_3    0.0
cluster_4    0.0
Name: 6776T>C, dtype: float64

In [55]:
all_cell_variant_df["6776T>C"]

cluster_0    18.0
cluster_1     0.0
cluster_2     0.0
cluster_3     0.0
cluster_4     0.0
Name: 6776T>C, dtype: float64

In [56]:
# heteroplasmic ratio
heteroplasmic_df = all_cell_variant_df / total_coverage_variant_df

In [57]:
heteroplasmic_df["6776T>C"]

cluster_0    0.9
cluster_1    NaN
cluster_2    0.0
cluster_3    0.0
cluster_4    0.0
Name: 6776T>C, dtype: float64

In [62]:
# strand correlation
mask_idx = (fwd_cell_variant_df + rev_cell_variant_df) == 0  # set 0 on both strands to nan to exclude from correlation calculation
fwd_cell_variant_df[mask_idx] = np.nan
rev_cell_variant_df[mask_idx] = np.nan
variant_strand_corr = fwd_cell_variant_df.corrwith(rev_cell_variant_df).round(3)

In [63]:
variant_strand_corr

58T>C      -1.000
64C>T      -1.000
72T>A         NaN
73A>G       0.980
146T>C      0.997
            ...
16309A>G    1.000
16366C>T    0.999
16390G>A    0.999
16399A>G    1.000
16519T>C    0.985
Length: 459, dtype: float64

In [61]:
variant_strand_corr["6776T>C"]

nan

In [67]:
all_cell_variant_df.sum(), heteroplasmic_df.var()

(58T>C         2.0
 64C>T         2.0
 72T>A         2.0
 73A>G       490.0
 146T>C      169.0
             ...
 16309A>G    175.0
 16366C>T    185.0
 16390G>A    174.0
 16399A>G    155.0
 16519T>C    376.0
 Length: 459, dtype: float64,
 58T>C       0.000016
 64C>T       0.000014
 72T>A       0.000097
 73A>G       0.216640
 146T>C      0.188162
               ...
 16309A>G    0.191046
 16366C>T    0.182429
 16390G>A    0.193644
 16399A>G    0.186394
 16519T>C    0.244351
 Length: 459, dtype: float64)

In [64]:
# vmr
variant_mean = all_cell_variant_df.sum() / total_coverage_variant_df.sum()
variant_var = heteroplasmic_df.var()
variant_vmr = variant_var / (variant_mean + 0.00000000001)

In [70]:
(heteroplasmic_df >= 0.05).sum()

58T>C       0
64C>T       0
72T>A       0
73A>G       4
146T>C      2
           ..
16309A>G    2
16366C>T    2
16390G>A    1
16399A>G    1
16519T>C    3
Length: 459, dtype: int64

In [71]:
# compute other summary stats
variant_positon = [x[0] for x in variants]
variant_nucleotide = ["{}>{}".format(x[1], x[2]) for x in variants]
variant_n_cells_conf_detected = ((fwd_cell_variant_df >= 2) & (rev_cell_variant_df >= 2)).sum()
variant_n_cells_over_5 = (heteroplasmic_df >= 0.05).sum()
variant_n_cells_over_10 = (heteroplasmic_df >= 0.1).sum()
variant_n_cells_over_20 = (heteroplasmic_df >= 0.2).sum()
variant_n_cells_over_95 = (heteroplasmic_df >= 0.95).sum()
max_heteroplasmy = heteroplasmic_df.max()
variant_mean_coverage = total_coverage_variant_df.mean()

In [72]:
# pack summary stats
variant_output = pd.DataFrame(
    [
        variant_positon,
        variant_nucleotide,
        variant_names,
        variant_vmr,
        variant_mean,
        variant_var,
        variant_n_cells_conf_detected,
        variant_n_cells_over_5,
        variant_n_cells_over_10,
        variant_n_cells_over_20,
        variant_n_cells_over_95,
        max_heteroplasmy,
        variant_strand_corr,
        variant_mean_coverage,
    ]
).T
variant_output.columns = ["position", "nucleotide", "variant", "vmr", "mean", "variance", "n_cells_conf_detected", "n_cells_over_5", "n_cells_over_10", "n_cells_over_20", "n_cells_over_95", "max_heteroplasmy", "strand_correlation", "mean_coverage"]
variant_output[["vmr", "mean", "variance", "strand_correlation", "mean_coverage", "max_heteroplasmy"]] = variant_output[["vmr", "mean", "variance", "strand_correlation", "mean_coverage", "max_heteroplasmy"]].astype(float)

In [74]:
variant_output.query("variant == '6776T>C'")

,position,nucleotide,variant,vmr,mean,variance,n_cells_conf_detected,n_cells_over_5,n_cells_over_10,n_cells_over_20,n_cells_over_95,max_heteroplasmy,strand_correlation,mean_coverage
171,6776,T>C,6776T>C,0.50625,0.4,0.2025,0,1,1,1,0,0.9,NaN,9.0