In [199]:
!hostname

c-11-01

In [202]:
import sys
import gzip
import glob
import numpy as np
import pandas as pd

import matplotlib
from matplotlib import pyplot as plt

In [203]:
def load_mgatk_output(output_dir, mito_length):
    # assuming mgatk output naming convention
    base_files = [glob.glob(output_dir + "*.{}.txt.gz".format(nt))[0] for nt in "ATCG"]

    base_coverage_dict = dict()
    for i, nt in enumerate("ATCG"):
        cur_base_data = pd.read_csv(gzip.open(base_files[i]), header=None)

        # gather coverage for forward strand
        fwd_base_df = cur_base_data[[0, 1, 2]].pivot_table(index=1, columns=0)
        fwd_base_df.columns = [
            x[1] for x in fwd_base_df.columns.values
        ]  # flatten weird multiindex after pivot
        fwd_base_df.index.name = None
        # missing_pos = [x for x in range(1, mito_length + 1) if x not in fwd_base_df.columns]
        # fwd_base_df[missing_pos] = 0  # fill in missing positions
        all_columns = [x for x in range(1, mito_length + 1)]
        fwd_base_df = fwd_base_df.reindex(columns=all_columns, fill_value=0)
        fwd_base_df = fwd_base_df.fillna(0).sort_index(
            axis=1
        )  # assume all nan are true zeroes

        # gather coverage for forward strand
        rev_base_df = cur_base_data[[0, 1, 3]].pivot_table(index=1, columns=0)
        rev_base_df.columns = [x[1] for x in rev_base_df.columns.values]
        rev_base_df.index.name = None
        # missing_pos = [x for x in range(1, mito_length + 1) if x not in rev_base_df.columns]
        # rev_base_df[missing_pos] = 0
        all_columns = [x for x in range(1, mito_length + 1)]
        rev_base_df = rev_base_df.reindex(columns=all_columns, fill_value=0)
        rev_base_df = rev_base_df.fillna(0).sort_index(axis=1)

        # organize base data into a dict
        base_coverage_dict[nt] = (fwd_base_df, rev_base_df)

    return base_coverage_dict


def gather_possible_variants(base_coverage_dict, reference_file):
    # sum across cells and strands for each base and position
    aggregated_genotype = pd.DataFrame(
        np.zeros((4, mito_length)),
        index=list("ATCG"),
        columns=np.arange(1, mito_length + 1),
    )
    for nt in base_coverage_dict:
        # sum across cells for each strand separately
        fwd_base_df, rev_base_df = base_coverage_dict[nt]
        fwd_base_sum, rev_base_sum = fwd_base_df.sum(), rev_base_df.sum()

        # sequencing artifact if a base/position is only nonzero for one strand across cells, ignore them
        masking = ~(
            (fwd_base_sum > 0) & (rev_base_sum > 0)
        )  # True if position not >0 for both strands
        fwd_base_sum[masking], rev_base_sum[masking] = 0, 0

        # sum across strands
        aggregated_genotype.loc[nt, :] = fwd_base_sum + rev_base_sum

    # make a reference set of tuples (pos, ref_base)
    ref_set = [x.strip().split() for x in open(reference_file, "r").readlines()]
    ref_N_positions = [int(x[0]) for x in ref_set if x[1].upper() not in letters]
    ref_set = set(
        [(int(x[0]), x[1].upper()) for x in ref_set if x[1].upper() in letters]
    )
    ref_dict = dict(ref_set)

    # make an observed set of tuples which are nonzero
    non_zero_idx = np.where(aggregated_genotype > 0)
    non_zero_bases = [letters[i] for i in non_zero_idx[0]]
    non_zero_pos = [int(i + 1) for i in non_zero_idx[1]]
    observed_set = list(zip(non_zero_pos, non_zero_bases))
    observed_set = set(
        [x for x in observed_set if x[0] not in ref_N_positions]
    )  # disregard positions in ref with N

    # take difference between observed and reference
    variant_set = observed_set - ref_set
    variants = sorted(
        [(x[0], ref_dict[x[0]], x[1]) for x in list(variant_set)], key=lambda x: x[0]
    )  # (pos, ref base, obs base)

    return variants

In [204]:
# sys.argv[1]
MGATK_OUT_DIR = "/scr1/users/liuc9/mitochondrial/realdata/01-Sci_Immunol_32651212/cromwell-executions/SCMTAH/022e0012-d8fc-4f0b-89d8-86004847b04a/call-call_mt_variants/execution/cell/final/"
sample_prefix = "cell"  # sys.argv[2]
mito_length = 16569  # int(sys.argv[3])  # 16569
low_coverage_threshold = 10  # int(sys.argv[4])  # 10
mito_genome = "MT"  # sys.argv[5]  # chrM

In [35]:
letters = list("ATCG")

In [42]:
# load_mgatk_output

output_dir = MGATK_OUT_DIR
mito_lenght = mito_length

base_files = [glob.glob(output_dir + "*.{}.txt.gz".format(nt))[0] for nt in "ATCG"]

base_coverage_dict = dict()

# for i, nt in enumerate("ATCG"):
#     cur_base_data = pd.read_csv(gzip.open(base_files[i]), header=None)
i = 0

cur_base_data = pd.read_csv(gzip.open(base_files[i]), header=None)

In [46]:
cur_base_data

             0                   1  2  3
0          341  TTCCTTCTCAAGTGGG-1  0  1
1          350  TTCCTTCTCAAGTGGG-1  0  2
2          351  TTCCTTCTCAAGTGGG-1  0  2
3          352  TTCCTTCTCAAGTGGG-1  0  2
4          357  TTCCTTCTCAAGTGGG-1  0  2
...        ...                 ... .. ..
5813669  12961  TTCCTTCCAGTCAGCC-1  1  0
5813670  12967  TTCCTTCCAGTCAGCC-1  1  0
5813671  12972  TTCCTTCCAGTCAGCC-1  1  0
5813672  12975  TTCCTTCCAGTCAGCC-1  1  0
5813673  12978  TTCCTTCCAGTCAGCC-1  1  0

[5813674 rows x 4 columns]

In [52]:
fwd_base_df = cur_base_data[[0, 1, 2]].pivot_table(index = 1, columns = 0)
fwd_base_df.columns = [x[1] for x in fwd_base_df.columns.values]
fwd_base_df.index.name = None

In [54]:
all_columns = [x for x in range(1, mito_length + 1)]
fwd_base_df = fwd_base_df.reindex(columns=all_columns, fill_value=0)
fwd_base_df = fwd_base_df.fillna(0).sort_index(axis=1)

In [56]:
# gather coverage for forward strand
rev_base_df = cur_base_data[[0, 1, 3]].pivot_table(index=1, columns=0)
rev_base_df.columns = [x[1] for x in rev_base_df.columns.values]
rev_base_df.index.name = None
# missing_pos = [x for x in range(1, mito_length + 1) if x not in rev_base_df.columns]
# rev_base_df[missing_pos] = 0
all_columns = [x for x in range(1, mito_length + 1)]
rev_base_df = rev_base_df.reindex(columns=all_columns, fill_value=0)
rev_base_df = rev_base_df.fillna(0).sort_index(axis=1)

In [57]:
base_coverage_dict[nt] = (fwd_base_df, rev_base_df)

In [58]:
base_coverage_dict

{'G': (                    1      2      3      4      5      6      7      8      \
  AAACCCACAAGAGCTG-1      0    0.0      0      0    0.0      0    0.0      0
  AAACCCACACAGCCAC-1      0    2.0      0      0    2.0      0    2.0      0
  AAACGAACAACGATCT-1      0    0.0      0      0    0.0      0    0.0      0
  AAACGAACACCAATTG-1      0    0.0      0      0    0.0      0    0.0      0
  AAACGAAGTACCGCGT-1      0    0.0      0      0    0.0      0    0.0      0
  ...                   ...    ...    ...    ...    ...    ...    ...    ...
  TTTGGTTAGTGGTCAG-1      0    0.0      0      0    0.0      0    0.0      0
  TTTGGTTGTACGAAAT-1      0    0.0      0      0    0.0      0    0.0      0
  TTTGTTGAGCACCAGA-1      0    0.0      0      0    0.0      0    0.0      0
  TTTGTTGAGGCTTCCG-1      0    0.0      0      0    0.0      0    0.0      0
  TTTGTTGCATGAAGCG-1      0    0.0      0      0    0.0      0    0.0      0

                      9      10     ...  16560  16561  16562  16563  16564  \
  AAACCCACAAGAGCTG-1      0      0  ...    0.0    0.0      0      0    0.0
  AAACCCACACAGCCAC-1      0      0  ...    0.0    4.0      0      0    4.0
  AAACGAACAACGATCT-1      0      0  ...    0.0    0.0      0      0    0.0
  AAACGAACACCAATTG-1      0      0  ...    0.0    0.0      0      0    0.0
  AAACGAAGTACCGCGT-1      0      0  ...    0.0    0.0      0      0    0.0
  ...                   ...    ...  ...    ...    ...    ...    ...    ...
  TTTGGTTAGTGGTCAG-1      0      0  ...    0.0    0.0      0      0    0.0
  TTTGGTTGTACGAAAT-1      0      0  ...    0.0    0.0      0      0    0.0
  TTTGTTGAGCACCAGA-1      0      0  ...    0.0    0.0      0      0    0.0
  TTTGTTGAGGCTTCCG-1      0      0  ...    0.0    0.0      0      0    0.0
  TTTGTTGCATGAAGCG-1      0      0  ...    0.0    0.0      0      0    0.0

                      16565  16566  16567  16568  16569
  AAACCCACAAGAGCTG-1      0    0.0    0.0      0      0
  AAACCCACACAGCCAC-1      0    0.0    4.0      0      0
  AAACGAACAACGATCT-1      0    0.0    0.0      0      0
  AAACGAACACCAATTG-1      0    0.0    0.0      0      0
  AAACGAAGTACCGCGT-1      0    0.0    0.0      0      0
  ...                   ...    ...    ...    ...    ...
  TTTGGTTAGTGGTCAG-1      0    0.0    0.0      0      0
  TTTGGTTGTACGAAAT-1      0    0.0    0.0      0      0
  TTTGTTGAGCACCAGA-1      0    0.0    0.0      0      0
  TTTGTTGAGGCTTCCG-1      0    0.0    0.0      0      0
  TTTGTTGCATGAAGCG-1      0    0.0    0.0      0      0

  [2368 rows x 16569 columns],
                      1      2      3      4      5      6      7      8      \
  AAACCCACAAGAGCTG-1      0    0.0      0      0    0.0      0    0.0      0
  AAACCCACACAGCCAC-1      0    1.0      0      0    1.0      0    1.0      0
  AAACGAACAACGATCT-1      0    0.0      0      0    0.0      0    0.0      0
  AAACGAACACCAATTG-1      0    0.0      0      0    0.0      0    0.0      0
  AAACGAAGTACCGCGT-1      0    0.0      0      0    0.0      0    0.0      0
  ...                   ...    ...    ...    ...    ...    ...    ...    ...
  TTTGGTTAGTGGTCAG-1      0    0.0      0      0    1.0      0    1.0      0
  TTTGGTTGTACGAAAT-1      0    0.0      0      0    0.0      0    0.0      0
  TTTGTTGAGCACCAGA-1      0    0.0      0      0    0.0      0    0.0      0
  TTTGTTGAGGCTTCCG-1      0    0.0      0      0    0.0      0    0.0      0
  TTTGTTGCATGAAGCG-1      0    0.0      0      0    0.0      0    0.0      0

                      9      10     ...  16560  16561  16562  16563  16564  \
  AAACCCACAAGAGCTG-1      0      0  ...    0.0    0.0      0      0    0.0
  AAACCCACACAGCCAC-1      0      0  ...    0.0    1.0      0      0    1.0
  AAACGAACAACGATCT-1      0      0  ...    0.0    0.0      0      0    0.0
  AAACGAACACCAATTG-1      0      0  ...    0.0    0.0      0      0    0.0
  AAACGAAGTACCGCGT-1      0      0  ...    0.0    0.0      0      0    0.0
  ...                   ...    ...  ...    ...    ...    ...    ...    ...
  TTTGGTTAGTGGTCAG-1      0      0  ...    0.0    1.0      0      0    1.0
  TTTGGTTGTACGAAAT-1      0      0  ...    0.0    0.0      0      0    0.0
  TTTGTTGAGCACCAGA-1      0      0  ...    0.0    0.0      0      0    0.0
  TTTGTTGAGGCTTCCG-1      0      0  ...    0.0    0.0      0      0    0.0
  TTTGTTGCATGAAGCG-1      0      0  ...    0.0    0.0      0      0    0.0

                      16565  16566  16567  16568  16569
  AAACCCACAAGAGCTG-1      0    0.0    0.0      0      0
  AAACCCACACAGCCAC-1      0    0.0    1.0      0      0
  AAACGAACAACGATCT-1      0    0.0    0.0      0      0
  AAACGAACACCAATTG-1      0    0.0    0.0      0      0
  AAACGAAGTACCGCGT-1      0    0.0    0.0      0      0
  ...                   ...    ...    ...    ...    ...
  TTTGGTTAGTGGTCAG-1      0    0.0    1.0      0      0
  TTTGGTTGTACGAAAT-1      0    0.0    0.0      0      0
  TTTGTTGAGCACCAGA-1      0    0.0    0.0      0      0
  TTTGTTGAGGCTTCCG-1      0    0.0    0.0      0      0
  TTTGTTGCATGAAGCG-1      0    0.0    0.0      0      0

  [2368 rows x 16569 columns])}

In [59]:
base_coverage_dict = load_mgatk_output(MGATK_OUT_DIR, mito_length)

In [63]:
cell_barcodes = base_coverage_dict["A"][0].index

In [64]:
cell_barcodes

Index(['AAACCCACAAGAGCTG-1', 'AAACCCACACAGCCAC-1', 'AAACGAACAACGATCT-1',
       'AAACGAACACCAATTG-1', 'AAACGAAGTACCGCGT-1', 'AAACGAATCAATCTCT-1',
       'AAACGAATCCGTTTCG-1', 'AAACGCTAGTCCTACA-1', 'AAACGCTGTAATCAGA-1',
       'AAAGGATGTATACCCA-1',
       ...
       'TTTGATCCATGAAGCG-1', 'TTTGATCTCAGCCTCT-1', 'TTTGATCTCGTCAGAT-1',
       'TTTGGAGGTGCAACGA-1', 'TTTGGTTAGGCAGTCA-1', 'TTTGGTTAGTGGTCAG-1',
       'TTTGGTTGTACGAAAT-1', 'TTTGTTGAGCACCAGA-1', 'TTTGTTGAGGCTTCCG-1',
       'TTTGTTGCATGAAGCG-1'],
      dtype='object', length=2368)

In [66]:
# total coverage per position per cell

total_coverage = pd.DataFrame(
    np.zeros((len(cell_barcodes), mito_length)),
    index=cell_barcodes,
    columns=np.arange(1, mito_length + 1),
)
total_coverage

,1,2,3,4,5,6,7,8,9,10,...,16560,16561,16562,16563,16564,16565,16566,16567,16568,16569
AAACCCACAAGAGCTG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACCCACACAGCCAC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAACAACGATCT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAACACCAATTG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAAGTACCGCGT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGTTAGTGGTCAG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGGTTGTACGAAAT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGAGCACCAGA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGAGGCTTCCG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGCATGAAGCG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [67]:
for nt in base_coverage_dict:
    total_coverage += base_coverage_dict[nt][0]
    total_coverage += base_coverage_dict[nt][1]

In [68]:
total_coverage

,1,2,3,4,5,6,7,8,9,10,...,16560,16561,16562,16563,16564,16565,16566,16567,16568,16569
AAACCCACAAGAGCTG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACCCACACAGCCAC-1,2.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0,4.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,3.0
AAACGAACAACGATCT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAACACCAATTG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAAGTACCGCGT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGTTAGTGGTCAG-1,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
TTTGGTTGTACGAAAT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGAGCACCAGA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGAGGCTTCCG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGCATGAAGCG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [71]:
total_coverage.mean(axis = 1)

AAACCCACAAGAGCTG-1     26.099523
AAACCCACACAGCCAC-1    124.033074
AAACGAACAACGATCT-1     12.782546
AAACGAACACCAATTG-1      0.299113
AAACGAAGTACCGCGT-1     59.352767
                         ...
TTTGGTTAGTGGTCAG-1     31.739936
TTTGGTTGTACGAAAT-1     19.745066
TTTGTTGAGCACCAGA-1     60.985274
TTTGTTGAGGCTTCCG-1     30.957089
TTTGTTGCATGAAGCG-1      0.103989
Length: 2368, dtype: float64

In [72]:
# exclude low coverage cells from variant calling

cell_barcodes = total_coverage.index[
    total_coverage.mean(axis=1) > low_coverage_threshold
]

In [73]:
for nt in base_coverage_dict:
    base_coverage_dict[nt] = (
        base_coverage_dict[nt][0].loc[cell_barcodes, :],
        base_coverage_dict[nt][1].loc[cell_barcodes, :],
    )
total_coverage = total_coverage.loc[cell_barcodes, :]

In [76]:
reference_file = MGATK_OUT_DIR + mito_genome + "_refAllele.txt"

aggregated_genotype = pd.DataFrame(
  np.zeros((4, len(mito_genome))),
  index = list("ATCG"),
  columns = np.arange(1, len(mito_genome) + 1)
)

In [78]:
nt = "A"

In [79]:
fwd_base_df, rev_base_df = base_coverage_dict[nt]
fwd_base_sum, rev_base_sum = fwd_base_df.sum(), rev_base_df.sum()

In [90]:
masking = ~((fwd_base_sum > 0) & (rev_base_sum > 0))
fwd_base_sum[masking], rev_base_sum[masking] = 0, 0

In [94]:
aggregated_genotype = pd.DataFrame(np.zeros((4, mito_length)), index=list("ATCG"), columns=np.arange(1, mito_length + 1))
for nt in base_coverage_dict:
    # sum across cells for each strand separately
    fwd_base_df, rev_base_df = base_coverage_dict[nt]
    fwd_base_sum, rev_base_sum = fwd_base_df.sum(), rev_base_df.sum()

    # sequencing artifact if a base/position is only nonzero for one strand across cells, ignore them
    masking = ~((fwd_base_sum > 0) & (rev_base_sum > 0))  # True if position not >0 for both strands
    fwd_base_sum[masking], rev_base_sum[masking] = 0, 0

    # sum across strands
    aggregated_genotype.loc[nt, :] = fwd_base_sum + rev_base_sum

In [95]:
aggregated_genotype

,1,2,3,4,5,6,7,8,9,10,...,16560,16561,16562,16563,16564,16565,16566,16567,16568,16569
A,0.0,564.0,0.0,0.0,706.0,0.0,814.0,0.0,0.0,0.0,...,0.0,2030.0,0.0,0.0,1926.0,0.0,0.0,1843.0,0.0,0.0
T,0.0,0.0,601.0,0.0,0.0,0.0,0.0,0.0,0.0,973.0,...,0.0,0.0,2005.0,0.0,0.0,0.0,0.0,0.0,1796.0,0.0
C,0.0,0.0,0.0,686.0,0.0,789.0,0.0,0.0,0.0,0.0,...,2136.0,3.0,0.0,1984.0,0.0,1910.0,0.0,0.0,0.0,0.0
G,488.0,0.0,0.0,0.0,0.0,0.0,0.0,883.0,923.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1860.0,0.0,0.0,1646.0

In [96]:
ref_set = [x.strip().split() for x in open(reference_file, "r").readlines()]

In [99]:
ref_set[:4]

[['1', 'G'], ['2', 'A'], ['3', 'T'], ['4', 'C']]

In [100]:
ref_N_positions = [int(x[0]) for x in ref_set if x[1].upper() not in letters]

In [101]:
ref_N_positions

[3107]

In [102]:

ref_set = set([(int(x[0]), x[1].upper()) for x in ref_set if x[1].upper() in letters])
ref_dict = dict(ref_set)

In [106]:
aggregated_genotype

,1,2,3,4,5,6,7,8,9,10,...,16560,16561,16562,16563,16564,16565,16566,16567,16568,16569
A,0.0,564.0,0.0,0.0,706.0,0.0,814.0,0.0,0.0,0.0,...,0.0,2030.0,0.0,0.0,1926.0,0.0,0.0,1843.0,0.0,0.0
T,0.0,0.0,601.0,0.0,0.0,0.0,0.0,0.0,0.0,973.0,...,0.0,0.0,2005.0,0.0,0.0,0.0,0.0,0.0,1796.0,0.0
C,0.0,0.0,0.0,686.0,0.0,789.0,0.0,0.0,0.0,0.0,...,2136.0,3.0,0.0,1984.0,0.0,1910.0,0.0,0.0,0.0,0.0
G,488.0,0.0,0.0,0.0,0.0,0.0,0.0,883.0,923.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1860.0,0.0,0.0,1646.0

In [111]:
a = pd.DataFrame({'a': [1, 0, 3], 'b': [4, 5, 6]})

In [114]:
a

   a  b
0  1  4
1  0  5
2  3  6

In [113]:
np.where(a > 0)

(array([0, 0, 1, 2, 2]), array([0, 1, 1, 0, 1]))

In [119]:
aggregated_genotype

,1,2,3,4,5,6,7,8,9,10,...,16560,16561,16562,16563,16564,16565,16566,16567,16568,16569
A,0.0,564.0,0.0,0.0,706.0,0.0,814.0,0.0,0.0,0.0,...,0.0,2030.0,0.0,0.0,1926.0,0.0,0.0,1843.0,0.0,0.0
T,0.0,0.0,601.0,0.0,0.0,0.0,0.0,0.0,0.0,973.0,...,0.0,0.0,2005.0,0.0,0.0,0.0,0.0,0.0,1796.0,0.0
C,0.0,0.0,0.0,686.0,0.0,789.0,0.0,0.0,0.0,0.0,...,2136.0,3.0,0.0,1984.0,0.0,1910.0,0.0,0.0,0.0,0.0
G,488.0,0.0,0.0,0.0,0.0,0.0,0.0,883.0,923.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1860.0,0.0,0.0,1646.0

In [139]:
non_zero_idx = np.where(aggregated_genotype > 0)

In [140]:
non_zero_bases = [letters[i] for i in non_zero_idx[0]]
non_zero_pos = [int(i + 1) for i in non_zero_idx[1]]

In [141]:
non_zero_bases[:4]

['A', 'A', 'A', 'A']

In [142]:
non_zero_pos[:4]

[2, 5, 7, 13]

In [143]:
observed_set = list(zip(non_zero_pos, non_zero_base))

In [144]:
observed_set[:5]

[(2, 'A'), (5, 'A'), (7, 'A'), (13, 'A'), (16, 'A')]

In [145]:
bserved_set = set([x for x in observed_set if x[0] not in ref_N_positions])  # disregard position

In [151]:
bserved_set[0:10]

TypeError: 'set' object is not subscriptable

In [146]:
list(bserved_set)[0:10]

[(2120, 'T'),
 (8378, 'A'),
 (5798, 'C'),
 (15803, 'G'),
 (14009, 'T'),
 (6205, 'G'),
 (5809, 'G'),
 (5943, 'G'),
 (2808, 'T'),
 (2150, 'T')]

In [147]:
list(ref_set)[0:10]

[(11094, 'C'),
 (5992, 'G'),
 (617, 'G'),
 (221, 'G'),
 (2473, 'A'),
 (8378, 'A'),
 (13887, 'A'),
 (10456, 'A'),
 (4685, 'A'),
 (10328, 'A')]

In [153]:
variant_set = set(observed_set) - set(ref_set)

In [155]:
variant_set

{(11228, 'C'),
 (2120, 'T'),
 (10832, 'C'),
 (13796, 'T'),
 (14283, 'A'),
 (289, 'C'),
 (300, 'G'),
 (11273, 'T'),
 (7976, 'T'),
 (14100, 'A'),
 (13838, 'A'),
 (14951, 'C'),
 (11124, 'C'),
 (11258, 'C'),
 (1888, 'T'),
 (14313, 'A'),
 (14051, 'A'),
 (11733, 'C'),
 (14506, 'C'),
 (11303, 'T'),
 (11075, 'C'),
 (13777, 'T'),
 (11209, 'C'),
 (8621, 'A'),
 (14130, 'A'),
 (13868, 'A'),
 (6269, 'T'),
 (13310, 'G'),
 (11778, 'T'),
 (15388, 'G'),
 (14343, 'A'),
 (3518, 'C'),
 (14536, 'C'),
 (3925, 'G'),
 (15339, 'G'),
 (3663, 'G'),
 (406, 'A'),
 (14294, 'A'),
 (8523, 'A'),
 (3731, 'C'),
 (9468, 'T'),
 (3563, 'T'),
 (14977, 'T'),
 (11546, 'T'),
 (6524, 'A'),
 (3810, 'C'),
 (8044, 'G'),
 (9285, 'T'),
 (14566, 'C'),
 (14324, 'A'),
 (3499, 'C'),
 (13108, 'G'),
 (34, 'T'),
 (387, 'A'),
 (11109, 'G'),
 (14958, 'T'),
 (6018, 'T'),
 (3791, 'C'),
 (9266, 'T'),
 (11831, 'A'),
 (10470, 'C'),
 (11139, 'G'),
 (7173, 'C'),
 (7842, 'G'),
 (13157, 'C'),
 (12499, 'C'),
 (9692, 'T'),
 (3787, 'T'),
 (3921, 'T'),
 (11565, 'G'),
 (11303, 'G'),
 (12940, 'T'),
 (15371, 'A'),
 (9600, 'A'),
 (11109, 'C'),
 (10713, 'C'),
 (13019, 'T'),
 (7248, 'T'),
 (11254, 'G'),
 (6986, 'T'),
 (10075, 'A'),
 (10926, 'C'),
 (1294, 'T'),
 (11139, 'C'),
 (10743, 'C'),
 (16252, 'C'),
 (16386, 'C'),
 (11284, 'G'),
 (13932, 'A'),
 (15748, 'A'),
 (10956, 'C'),
 (5413, 'T'),
 (10922, 'T'),
 (10694, 'C'),
 (10298, 'C'),
 (4923, 'C'),
 (8240, 'A'),
 (8433, 'C'),
 (9498, 'G'),
 (3197, 'G'),
 (13942, 'C'),
 (10739, 'T'),
 (10907, 'C'),
 (16416, 'C'),
 (5805, 'G'),
 (13962, 'A'),
 (8512, 'C'),
 (14417, 'C'),
 (11214, 'T'),
 (14551, 'C'),
 (3544, 'G'),
 (13255, 'A'),
 (8725, 'C'),
 (8691, 'T'),
 (3623, 'G'),
 (5260, 'T'),
 (10507, 'T'),
 (14447, 'C'),
 (14413, 'T'),
 (14581, 'C'),
 (11378, 'T'),
 (14319, 'C'),
 (9083, 'G'),
 (11335, 'A'),
 (11073, 'A'),
 (2984, 'C'),
 (8721, 'T'),
 (7218, 'G'),
 (14398, 'C'),
 (14002, 'C'),
 (11195, 'T'),
 (14364, 'T'),
 (14215, 'C'),
 (8444, 'C'),
 (14349, 'C'),
 (11237, 'A'),
 (6183, 'C'),
 (14656, 'T'),
 (12757, 'G'),
 (298, 'A'),
 (11450, 'A'),
 (11054, 'A'),
 (6396, 'C'),
 (14473, 'T'),
 (14607, 'T'),
 (966, 'C'),
 (6609, 'C'),
 (7278, 'G'),
 (14424, 'T'),
 (2748, 'T'),
 (3363, 'A'),
 (9268, 'A'),
 (14558, 'T'),
 (15628, 'C'),
 (259, 'C'),
 (3576, 'A'),
 (9085, 'A'),
 (12772, 'T'),
 (6471, 'T'),
 (6456, 'C'),
 (913, 'T'),
 (6060, 'C'),
 (12802, 'T'),
 (10313, 'C'),
 (4012, 'C'),
 (15426, 'C'),
 (16491, 'G'),
 (7656, 'C'),
 (8721, 'G'),
 (10754, 'T'),
 (10130, 'C'),
 (9734, 'C'),
 (15639, 'C'),
 (13774, 'C'),
 (4042, 'C'),
 (8672, 'G'),
 (13853, 'C'),
 (2177, 'C'),
 (8751, 'G'),
 (2584, 'G'),
 (15897, 'T'),
 (10522, 'T'),
 (4830, 'T'),
 (13542, 'C'),
 (14345, 'G'),
 (14279, 'C'),
 (13849, 'T'),
 (14424, 'G'),
 (10905, 'A'),
 (11360, 'C'),
 (6520, 'G'),
 (2158, 'C'),
 (2827, 'G'),
 (11118, 'A'),
 (4951, 'A'),
 (6733, 'G'),
 (14047, 'C'),
 (16444, 'A'),
 (6684, 'G'),
 (6288, 'G'),
 (14226, 'T'),
 (2154, 'T'),
 (189, 'C'),
 (14305, 'T'),
 (11341, 'C'),
 (334, 'G'),
 (8625, 'A'),
 (402, 'C'),
 (14518, 'T'),
 (6714, 'G'),
 (2446, 'T'),
 (8123, 'C'),
 (8089, 'T'),
 (2799, 'A'),
 (8442, 'A'),
 (11371, 'C'),
 (5996, 'C'),
 (14426, 'A'),
 (8655, 'A'),
 (16342, 'G'),
 (3601, 'C'),
 (15684, 'G'),
 (11812, 'T'),
 (14286, 'T'),
 (14377, 'A'),
 (8606, 'A'),
 (3814, 'C'),
 (383, 'C'),
 (6516, 'T'),
 (215, 'T'),
 (11629, 'T'),
 (11797, 'C'),
 (11401, 'C'),
 (2780, 'A'),
 (8685, 'A'),
 (14194, 'A'),
 (14328, 'A'),
 (4027, 'C'),
 (3631, 'C'),
 (14407, 'A'),
 (8636, 'A'),
 (14541, 'A'),
 (15486, 'T'),
 (9091, 'C'),
 (6022, 'T'),
 (14620, 'A'),
 (7761, 'G'),
 (12006, 'T'),
 (12621, 'A'),
 (3157, 'A'),
 (13076, 'C'),
 (13879, 'G'),
 (15650, 'T'),
 (13355, 'G'),
 (11914, 'A'),
 (2020, 'G'),
 (4053, 'T'),
 (13830, 'G'),
 (8059, 'G'),
 (12389, 'A'),
 (6618, 'A'),
 (6222, 'A'),
 (7731, 'C'),
 (11569, 'G'),
 (12978, 'C'),
 (15284, 'T'),
 (3608, 'T'),
 (13781, 'G'),
 (7152, 'C'),
 (13057, 'C'),
 (11386, 'G'),
 (13191, 'C'),
 (15497, 'T'),
 (1856, 'C'),
 (13498, 'T'),
 (1990, 'C'),
 (13008, 'C'),
 (11337, 'G'),
 (15667, 'A'),
 (10292, 'A'),
 (6465, 'A'),
 (9634, 'A'),
 (11009, 'C'),
 (398, 'G'),
 (10747, 'C'),
 (11812, 'G'),
 (13483, 'C'),
 (13221, 'C'),
 (11222, 'C'),
 (10826, 'C'),
 (8019, 'T'),
 (10960, 'C'),
 (16469, 'C'),
 (11629, 'G'),
 (2199, 'T'),
 (13479, 'T'),
 (13832, 'A'),
 (8061, 'A'),
 (379, 'G'),
 (16499, 'C'),
 (117, 'G'),
 (16237, 'C'),
 (15861, 'A'),
 (14500, 'C'),
 (15565, 'G'),
 (11297, 'T'),
 (14634, 'C'),
 (14238, 'C'),
 (8729, 'C'),
 (16316, 'C'),
 (2229, 'T'),
 (10941, 'C'),
 (13338, 'A'),
 (14451, 'C'),
 (11020, 'C'),
 (2046, 'T'),
 (11823, 'G'),
 (13551, 'A'),
 (9021, 'C'),
 (14530, 'C'),
 (9155, 'C'),
 (3919, 'G'),
 (11233, 'C'),
 (15467, 'G'),
 (10971, 'C'),
 (8710, 'C'),
 (11278, 'T'),
 (14219, 'C'),
 (13977, 'A'),
 (13285, 'G'),
 (8789, 'C'),
 (14660, 'T'),
 (14432, 'C'),
 (3425, 'G'),
 (11363, 'T'),
 (15135, 'T'),
 (14249, 'C'),
 (6286, 'A'),
 (11795, 'A'),
 (11533, 'A'),
 (6741, 'C'),
 (970, 'C'),
 (3538, 'T'),
 (3672, 'T'),
 (15086, 'T'),
 (3014, 'T'),
 (11088, 'A'),
 (12859, 'C'),
 (6558, 'C'),
 (8770, 'C'),
 (3580, 'A'),
 (11825, 'A'),
 (11563, 'A'),
 (12676, 'C'),
 (8949, 'T'),
 (9302, 'A'),
 (362, 'A'),
 (15924, 'C'),
 (11218, 'G'),
 (10560, 'G'),
 (14537, 'T'),
 (13034, 'G'),
 (3610, 'A'),
 (13068, 'T'),
 (4868, 'G'),
 (15499, 'A'),
 (11510, 'G'),
 (6980, 'T'),
 (10590, 'G'),
 (6718, 'T'),
 (3683, 'T'),
 (6490, 'C'),
 (12976, 'A'),
 (343, 'A'),
 (10658, 'C'),
 (5160, 'G'),
 (5294, 'G'),
 (6931, 'T'),
 (13049, 'T'),
 (12653, 'T'),
 (13006, 'A'),
 (13857, 'C'),
 (4917, 'C'),
 (2850, 'G'),
 (14264, 'G'),
 (10833, 'G'),
 (7710, 'A'),
 (14070, 'C'),
 (14477, 'G'),
 (15752, 'C'),
 (11046, 'G'),
 (1007, 'T'),
 (13887, 'C'),
 (10818, 'T'),
 (11259, 'G'),
 (8591, 'C'),
 (6524, 'G'),
 (2424, 'C'),
 (8602, 'G'),
 (11031, 'T'),
 (10635, 'T'),
 (8736, 'G'),
 (832, 'G'),
 (2910, 'G'),
 (4943, 'T'),
 (14324, 'G'),
 (2648, 'G'),
 (11201, 'A'),
 (10939, 'A'),
 (7246, 'A'),
 (11656, 'C'),
 (14358, 'T'),
 (14096, 'T'),
 (5156, 'T'),
 (14264, 'C'),
 (14537, 'G'),
 (7963, 'C'),
 (11152, 'A'),
 (10756, 'A'),
 (8666, 'T'),
 (7163, 'G'),
 (11607, 'C'),
 (14309, 'T'),
 (6505, 'G'),
 (14081, 'C'),
 (11231, 'A'),
 (10969, 'A'),
 (16478, 'A'),
 (7242, 'G'),
 (8879, 'T'),
 (14388, 'T'),
 (8617, 'T'),
 (8389, 'C'),
 (14032, 'C'),
 (4924, 'T'),
 (10920, 'A'),
 (6390, 'C'),
 (6524, 'C'),
 (10228, 'G'),
 (14601, 'T'),
 (7193, 'G'),
 (892, 'G'),
 (3016, 'A'),
 (11395, 'A'),
 (10999, 'A'),
 (16508, 'A'),
 (11133, 'A'),
 (4832, 'A'),
 (14552, 'T'),
 (14643, 'A'),
 (11212, 'A'),
 (10950, 'A'),
 (9996, 'G'),
 (14369, 'T'),
 (12470, 'G'),
 (14460, 'A'),
 (14198, 'A'),
 (14582, 'T'),
 (14320, 'T'),
 (9426, 'A'),
 (9164, 'A'),
 (6550, 'T'),
 (6322, 'C'),
 (14490, 'A'),
 (15603, 'C'),
 (3927, 'C'),
 (3665, 'C'),
 (12138, 'T'),
 (368, 'C'),
 (11614, 'T'),
 (14441, 'A'),
 (14145, 'G'),
 (6580, 'T'),
 (12089, 'T'),
 (8749, 'A'),
 (2978, 'A'),
 (3957, 'C'),
 (13962, 'G'),
 (15995, 'T'),
 (10665, 'G'),
 (3433, 'C'),
 (11906, 'T'),
 (12040, 'T'),
 (8666, 'G'),
 (15812, 'T'),
 (8404, 'G'),
 (15584, 'C'),
 (9813, 'C'),
 (15550, 'T'),
 (6610, 'T'),
 (16387, 'G'),
 (11865, 'G'),
 (15748, 'C'),
 (4072, 'C'),
 (9809, 'T'),
 (6469, 'A'),
 (2073, 'C'),
 (13353, 'C'),
 (7320, 'C'),
 (13894, 'G'),
 (15927, 'T'),
 (6944, 'A'),
 (13928, 'T'),
 (13304, 'C'),
 (13042, 'C'),
 (15610, 'T'),
 (11043, 'C'),
 (2103, 'C'),
 (13779, 'C'),
 (13745, 'T'),
 (11256, 'C'),
 (10880, 'A'),
 (16261, 'A'),
 (5430, 'C'),
 (11469, 'C'),
 (6233, 'G'),
 (13909, 'T'),
 (14262, 'A'),
 (5381, 'C'),
 (2574, 'T'),
 (9615, 'G'),
 (279, 'G'),
 (5119, 'C'),
 (1916, 'T'),
 (6184, 'G'),
 (16291, 'A'),
 (11103, 'C'),
 (10841, 'C'),
 (14158, 'A'),
 (14292, 'A'),
 (15416, 'G'),
 (11282, 'T'),
 (14109, 'A'),
 (13847, 'A'),
 (15629, 'G'),
 (81, 'T'),
 (9858, 'G'),
 (11267, 'C'),
 (13969, 'T'),
 (8155, 'A'),
 (14060, 'A'),
 (14777, 'C'),
 (3101, 'C'),
 (15580, 'G'),
 (11312, 'T'),
 (14535, 'A'),
 (8106, 'A'),
 (13319, 'G'),
 (15124, 'C'),
 (12012, 'A'),
 (2280, 'A'),
 (8581, 'A'),
 (8023, 'G'),
 (8774, 'C'),
 (11476, 'T'),
 (14303, 'A'),
 (12680, 'C'),
 (11555, 'T'),
 (11689, 'T'),
 (11646, 'A'),
 (8611, 'A'),
 (13824, 'G'),
 (3161, 'C'),
 (14575, 'C'),
 (6612, 'A'),
 (12972, 'C'),
 (7201, 'C'),
 (7870, 'G'),
 (6543, 'C'),
 (15184, 'C'),
 (3508, 'C'),
 (12661, 'C'),
 (15582, 'A'),
 (5426, 'G'),
 (7231, 'C'),
 (1292, 'T'),
 (12740, 'C'),
 (15442, 'T'),
 (13543, 'G'),
 (11544, 'G'),
 (11148, 'G'),
 (7851, 'G'),
 (3583, 'T'),
 (1015, 'C'),
 (15393, 'T'),
 (9841, 'A'),
 (16463, 'C'),
 (11361, 'G'),
 (12904, 'C'),
 (15697, 'A'),
 (15301, 'A'),
 (10771, 'C'),
 (10905, 'C'),
 (10916, 'G'),
 (1273, 'T'),
 (11050, 'G'),
 (3704, 'A'),
 (3838, 'A'),
 (3542, 'G'),
 (10688, 'T'),
 (10856, 'C'),
 (11263, 'G'),
 (15989, 'A'),
 (13253, 'A'),
 (4051, 'A'),
 (5426, 'C'),
 (4996, 'T'),
 (3572, 'G'),
 (11148, 'C'),
 (13941, 'A'),
 (13679, 'A'),
 (13283, 'A'),
 (14396, 'C'),
 (11193, 'T'),
 (3785, 'G'),
 (5422, 'T'),
 (8704, 'C'),
 (14347, 'C'),
 (11144, 'T'),
 (10748, 'T'),
 (10520, 'C'),
 (16391, 'T'),
 (5330, 'A'),
 (11235, 'A'),
 (2295, 'A'),
 (13971, 'A'),
 (12755, 'G'),
 (14560, 'C'),
 (9062, 'G'),
 (11448, 'A'),
 (14639, 'C'),
 (5360, 'A'),
 (2325, 'A'),
 (11003, 'A'),
 (8913, 'T'),
 (14160, 'T'),
 (8730, 'T'),
 (11671, 'C'),
 (11295, 'A'),
 (16246, 'G'),
 (11884, 'C'),
 (12949, 'G'),
 (14452, 'T'),
 (9034, 'A'),
 (287, 'C'),
 (14494, 'A'),
 (10767, 'G'),
 (15607, 'C'),
 (238, 'C'),
 (8711, 'T'),
 (3555, 'A'),
 (14969, 'A'),
 (9198, 'A'),
 (5371, 'A'),
 (15686, 'C'),
 (16489, 'G'),
 (12751, 'T'),
 (11731, 'C'),
 (14433, 'T'),
 (3506, 'A'),
 (75, 'A'),
 (15899, 'C'),
 (12602, 'C'),
 (10931, 'G'),
 (16440, 'G'),
 (6401, 'T'),
 (3585, 'A'),
 (10748, 'G'),
 (10352, 'G'),
 (6252, 'C'),
 (6967, 'A'),
 (9896, 'C'),
 (6693, 'T'),
 (15405, 'C'),
 (12689, 'A'),
 (3749, 'A'),
 (8700, 'G'),
 (15880, 'C'),
 (14422, 'G'),
 (10322, 'C'),
 (9926, 'C'),
 (8651, 'G'),
 (10060, 'C'),
 (13115, 'A'),
 (14635, 'G'),
 (15648, 'C'),
 (15614, 'T'),
 (12670, 'A'),
 (14045, 'C'),
 (8681, 'G'),
 (16223, 'T'),
 (15827, 'T'),
 (6978, 'A'),
 (13862, 'C'),
 (11929, 'G'),
 (14403, 'G'),
 (8632, 'G'),
 (10884, 'A'),
 (13907, 'T'),
 (11339, 'C'),
 (2399, 'C'),
 (2003, 'C'),
 (13813, 'C'),
 (10610, 'T'),
 (16515, 'T'),
 (11097, 'A'),
 (14026, 'C'),
 (6529, 'G'),
 (11369, 'C'),
 (14467, 'T'),
 (13843, 'C'),
 (7904, 'T'),
 (14162, 'A'),
 (4826, 'A'),
 (11582, 'C'),
 (302, 'C'),
 (14284, 'T'),
 (11320, 'C'),
 (6614, 'G'),
 (313, 'G'),
 (13794, 'C'),
 (10944, 'A'),
 (6286, 'C'),
 (8592, 'T'),
 (15633, 'G'),
 (6297, 'G'),
 (2425, 'T'),
 (11137, 'C'),
 (16404, 'A'),
 (15712, 'G'),
 (6069, 'T'),
 (11088, 'C'),
 (6248, 'G'),
 (8634, 'A'),
 (10712, 'A'),
 (10154, 'G'),
 (9758, 'G'),
 (283, 'C'),
 (14265, 'T'),
 (11301, 'C'),
 (8451, 'A'),
 (14356, 'A'),
 (13960, 'A'),
 (10925, 'A'),
 (15469, 'C'),
 (8926, 'A'),
 (14569, 'A'),
 (15682, 'C'),
 (6574, 'T'),
 (15693, 'G'),
 (10318, 'G'),
 (9922, 'G'),
 (11559, 'T'),
 (2710, 'A'),
 (8615, 'A'),
 (14520, 'A'),
 (14124, 'A'),
 (3561, 'C'),
 (11376, 'T'),
 (96, 'T'),
 (6220, 'A'),
 (14337, 'A'),
 (15712, 'C'),
 (3640, 'C'),
 (15678, 'T'),
 (15450, 'C'),
 (9149, 'C'),
 (15188, 'C'),
 (11985, 'T'),
 (309, 'T'),
 (8907, 'A'),
 (15757, 'T'),
 (7953, 'G'),
 (9362, 'C'),
 (7691, 'G'),
 (13151, 'G'),
 (6597, 'A'),
 (7314, 'C'),
 (12823, 'C'),
 (13888, 'G'),
 (4111, 'T'),
 (12957, 'C'),
 (3849, 'T'),
 (13432, 'C'),
 (7265, 'C'),
 (13170, 'C'),
 (15738, 'T'),
 (13443, 'G'),
 (10775, 'C'),
 (13477, 'T'),
 (13656, 'G'),
 (15646, 'A'),
 (10988, 'C'),
 (6148, 'G'),
 (12804, 'C'),
 (12938, 'C'),
 (11201, 'C'),
 (13017, 'C'),
 (15810, 'A'),
 (11018, 'C'),
 (11152, 'C'),
 (10756, 'C'),
 (11425, 'G'),
 (15627, 'A'),
 (13933, 'T'),
 (5064, 'C'),
 (11376, 'G'),
 (14024, 'A'),
 (14479, 'C'),
 (3868, 'G'),
 (11182, 'C'),
 (2074, 'T'),
 (2561, 'A'),
 (2165, 'A'),
 (1903, 'A'),
 (13317, 'A'),
 (11489, 'T'),
 (3685, 'G'),
 (14430, 'C'),
 (15495, 'G'),
 (388, 'G'),
 (13701, 'T'),
 (10737, 'C'),
 (13792, 'A'),
 (13530, 'A'),
 (8738, 'C'),
 (15312, 'G'),
 (9541, 'G'),
 (5441, 'C'),
 (5045, 'C'),
 (11178, 'T'),
 (14267, 'A'),
 (14005, 'A'),
 (15118, 'C'),
 (8689, 'C'),
 (14198, 'C'),
 (11391, 'T'),
 (5258, 'C'),
 (9096, 'G'),
 (15001, 'G'),
 (10733, 'T'),
 (11470, 'T'),
 (8506, 'C'),
 (14411, 'C'),
 (3800, 'G'),
 (10946, 'T'),
 (11299, 'A'),
 (2359, 'A'),
 (14035, 'A'),
 (8719, 'C'),
 (14456, 'T'),
 (14624, 'C'),
 (3617, 'G'),
 (11159, 'T'),
 (98, 'A'),
 (15327, 'T'),
 (9026, 'T'),
 (13428, 'G'),
 (8764, 'T'),
 (14441, 'C'),
 (8670, 'C'),
 (11372, 'T'),
 (311, 'A'),
 (1028, 'C'),
 (6933, 'C'),
 (8749, 'C'),
 (5375, 'A'),
 (11280, 'A'),
 (3547, 'T'),
 (9452, 'T'),
 (14961, 'T'),
 (8962, 'C'),
 (6963, 'C'),
 (6929, 'T'),
 (14516, 'T'),
 (8745, 'T'),
 (15661, 'A'),
 (3589, 'A'),
 (292, 'A'),
 (12685, 'C'),
 (6914, 'C'),
 (16523, 'G'),
 (13047, 'T'),
 (747, 'C'),
 (15082, 'A'),
 (11489, 'G'),
 (9171, 'T'),
 (14771, 'A'),
 (16280, 'C'),
 (1039, 'C'),
 (6682, 'C'),
 (7385, 'T'),
 (10861, 'G'),
 (5090, 'G'),
 (6727, 'T'),
 (12632, 'T'),
 (3649, 'A'),
 (15914, 'C'),
 (11208, 'G'),
 (8551, 'G'),
 (12924, 'T'),
 (11025, 'G'),
 (13015, 'A'),
 (3517, 'G'),
 (13866, 'C'),
 (15944, 'C'),
 (14273, 'G'),
 (11238, 'G'),
 (12966, 'A'),
 (13945, 'C'),
 (4971, 'T'),
 (8715, 'G'),
 (2482, 'C'),
 (3023, 'G'),
 (16336, 'T'),
 (8928, 'G'),
 (13130, 'A'),
 (12438, 'G'),
 (10906, 'T'),
 (12913, 'G'),
 (2512, 'C'),
 (6612, 'G'),
 (13926, 'C'),
 (1988, 'C'),
 (16457, 'A'),
 (14367, 'T'),
 (12864, 'G'),
 (8596, 'T'),
 (14501, 'T'),
 (13877, 'C'),
 (11423, 'A'),
 (11161, 'A'),
 (12681, 'G'),
 (14090, 'C'),
 (8151, 'T'),
 (11112, 'A'),
 (6331, 'G'),
 (14269, 'T'),
 (14488, 'A'),
 (14622, 'A'),
 (11191, 'A'),
 (6399, 'C'),
 (2538, 'T'),
 (14482, 'T'),
 (14086, 'T'),
 (14439, 'A'),
 (11142, 'A'),
 (6578, 'T'),
 (11463, 'C'),
 (14561, 'T'),
 (8790, 'T'),
 (8747, 'A'),
 (14390, 'A'),
 (12038, 'T'),
 (3906, 'C'),
 (475, 'C'),
 (6212, 'T'),
 (6380, 'C'),
 (11855, 'T'),
 (8777, 'A'),
 (14420, 'A'),
 (10693, 'G'),
 (4922, 'G'),
 (9366, 'C'),
 (15746, 'C'),
 (9579, 'C'),
 (15484, 'C'),
 (11885, 'T'),
 (12372, 'A'),
 (14154, 'G'),
 (3887, 'C'),
 (9792, 'C'),
 (6942, 'A'),
 (13302, 'C'),
 (10005, 'C'),
 (3704, 'C'),
 (6893, 'A'),
 (3462, 'A'),
 (10312, 'T'),
 (9916, 'T'),
 (8151, 'G'),
 (3883, 'T'),
 (14056, 'G'),
 (15912, 'A'),
 (7823, 'C'),
 (11661, 'G'),
 (13739, 'G'),
 (15772, 'T'),
 (7968, 'G'),
 (8364, 'G'),
 (12566, 'A'),
 (6365, 'G'),
 (8443, 'G'),
 (14348, 'G'),
 (3913, 'T'),
 (9818, 'T'),
 (2082, 'C'),
 (8656, 'G'),
 (7329, 'C'),
 (10646, 'A'),
 ...}

In [156]:
ref_dict[1]

'G'

In [158]:
variants = sorted([(x[0], ref_dict[x[0]], x[1]) for x in list(variant_set)], key=lambda x: x[0])

KeyError: 3107

In [110]:
non_zero_idx[1]

array([    1,     4,     6, ..., 16557, 16565, 16568])

In [82]:
masking

1         True
2        False
3         True
4         True
5        False
         ...
16565     True
16566     True
16567    False
16568     True
16569     True
Length: 16569, dtype: bool

In [75]:
reference_file

'/scr1/users/liuc9/mitochondrial/realdata/01-Sci_Immunol_32651212/cromwell-executions/SCMTAH/022e0012-d8fc-4f0b-89d8-86004847b04a/call-call_mt_variants/execution/cell/final/MT_refAllele.txt'

In [159]:
# cell positional variants
variants = gather_possible_variants(
    base_coverage_dict, MGATK_OUT_DIR + mito_genome + "_refAllele.txt"
)

In [163]:
len(variants)

6231

In [161]:
variant_names = ["{}{}>{}".format(x[0], x[1], x[2]) for x in variants]

In [162]:
variant_names

['34G>T',
 '39C>A',
 '45A>C',
 '46T>G',
 '49A>C',
 '51T>A',
 '52T>G',
 '58T>G',
 '65T>G',
 '73A>G',
 '75G>A',
 '76C>T',
 '76C>A',
 '79G>T',
 '81G>T',
 '82A>G',
 '91C>T',
 '96C>T',
 '96C>A',
 '97G>A',
 '98C>A',
 '106G>A',
 '110C>T',
 '110C>A',
 '117T>G',
 '121G>A',
 '125T>G',
 '134T>G',
 '137A>T',
 '138T>C',
 '145C>A',
 '149T>G',
 '150C>T',
 '154T>G',
 '157T>G',
 '163G>A',
 '169A>C',
 '172T>G',
 '173T>C',
 '175A>C',
 '182C>T',
 '183A>T',
 '183A>G',
 '187G>T',
 '189A>C',
 '195T>G',
 '199T>A',
 '201A>T',
 '215A>T',
 '219A>T',
 '221G>T',
 '222C>A',
 '225G>T',
 '227A>G',
 '229G>A',
 '229G>T',
 '230A>C',
 '237A>G',
 '237A>T',
 '238A>C',
 '239T>G',
 '240A>G',
 '242C>A',
 '248A>G',
 '249A>C',
 '254T>A',
 '257A>G',
 '259A>C',
 '263A>T',
 '263A>G',
 '264C>A',
 '265T>G',
 '266T>C',
 '269C>A',
 '270A>C',
 '272A>C',
 '274A>C',
 '276A>C',
 '278A>C',
 '279T>G',
 '280C>G',
 '282T>G',
 '283A>C',
 '284A>C',
 '286A>C',
 '287A>C',
 '288A>C',
 '289A>C',
 '290A>T',
 '291A>T',
 '292T>A',
 '292T>G',
 '293T>G',
 '297A>T',
 '297A>C',
 '298C>A',
 '300A>G',
 '300A>C',
 '301A>G',
 '301A>T',
 '301A>C',
 '302A>C',
 '302A>T',
 '303C>A',
 '306C>G',
 '308C>T',
 '309C>T',
 '310T>A',
 '310T>G',
 '310T>C',
 '311C>A',
 '313C>G',
 '314C>G',
 '318T>G',
 '321T>G',
 '322G>T',
 '326A>C',
 '327C>A',
 '328A>C',
 '331A>T',
 '333T>A',
 '333T>G',
 '334T>G',
 '337A>C',
 '338C>A',
 '339A>C',
 '341A>G',
 '341A>C',
 '342T>A',
 '342T>G',
 '343C>A',
 '346T>A',
 '349C>A',
 '350A>G',
 '351A>G',
 '352A>C',
 '353C>A',
 '354C>A',
 '356C>A',
 '357A>C',
 '362C>A',
 '364A>C',
 '365A>G',
 '366G>T',
 '368A>C',
 '369C>A',
 '370C>A',
 '371C>T',
 '372T>A',
 '372T>G',
 '375C>A',
 '376A>T',
 '377C>A',
 '378C>A',
 '378C>T',
 '379A>G',
 '380G>C',
 '381C>T',
 '382C>T',
 '383T>C',
 '383T>G',
 '383T>A',
 '384A>C',
 '386C>A',
 '387C>A',
 '387C>G',
 '388A>G',
 '388A>C',
 '389G>T',
 '390A>C',
 '391T>A',
 '391T>C',
 '391T>G',
 '392T>G',
 '392T>A',
 '393T>C',
 '394C>A',
 '395A>G',
 '396A>T',
 '396A>G',
 '398T>G',
 '398T>A',
 '399T>G',
 '400T>A',
 '400T>C',
 '400T>G',
 '401T>G',
 '402A>C',
 '402A>G',
 '404C>A',
 '405T>C',
 '405T>G',
 '406T>A',
 '406T>G',
 '408T>C',
 '409G>C',
 '411C>A',
 '475A>C',
 '503A>C',
 '505C>A',
 '531T>G',
 '687G>T',
 '697G>T',
 '745A>C',
 '746A>C',
 '747A>C',
 '750A>G',
 '773T>C',
 '810G>T',
 '812A>T',
 '831T>G',
 '832T>G',
 '839A>C',
 '840A>C',
 '844A>C',
 '871A>C',
 '885T>A',
 '888T>G',
 '890C>T',
 '892A>G',
 '903T>A',
 '905A>C',
 '913A>T',
 '914A>C',
 '921T>A',
 '923A>G',
 '924A>C',
 '925T>G',
 '937T>A',
 '938A>T',
 '940A>C',
 '942A>C',
 '949T>C',
 '953T>A',
 '955A>T',
 '957C>G',
 '960C>T',
 '961T>C',
 '966A>C',
 '967A>C',
 '969A>C',
 '970A>C',
 '972G>T',
 '976A>C',
 '988G>T',
 '991G>T',
 '994A>G',
 '995A>T',
 '997A>C',
 '999C>A',
 '1004G>T',
 '1005T>A',
 '1007G>T',
 '1010A>T',
 '1012A>T',
 '1014A>C',
 '1015A>C',
 '1017A>C',
 '1019A>T',
 '1028G>C',
 '1030G>T',
 '1032C>A',
 '1039A>C',
 '1041A>C',
 '1047A>C',
 '1055T>G',
 '1069A>C',
 '1085C>A',
 '1092G>C',
 '1096A>C',
 '1256A>T',
 '1259T>G',
 '1261C>T',
 '1268C>A',
 '1273G>T',
 '1273G>C',
 '1274C>A',
 '1276A>C',
 '1282G>T',
 '1289G>T',
 '1292A>T',
 '1294A>T',
 '1299A>T',
 '1299A>G',
 '1301G>T',
 '1303G>C',
 '1305A>T',
 '1306A>T',
 '1308T>A',
 '1313A>C',
 '1359T>C',
 '1361G>C',
 '1373T>C',
 '1398T>A',
 '1403A>C',
 '1404A>T',
 '1407T>C',
 '1438A>G',
 '1502A>C',
 '1527A>G',
 '1728T>A',
 '1830G>T',
 '1856A>C',
 '1859A>T',
 '1878T>C',
 '1878T>G',
 '1884G>T',
 '1888G>T',
 '1898A>T',
 '1903C>A',
 '1909A>C',
 '1916G>T',
 '1938A>C',
 '1952T>G',
 '1963A>T',
 '1969G>T',
 '1986A>G',
 '1987G>T',
 '1988G>C',
 '1990G>C',
 '1995A>C',
 '1999A>T',
 '2003A>C',
 '2007T>C',
 '2018G>T',
 '2020T>G',
 '2020T>A',
 '2034A>C',
 '2034A>G',
 '2035T>A',
 '2039A>T',
 '2045A>G',
 '2046C>T',
 '2052A>T',
 '2054T>G',
 '2055T>G',
 '2058C>A',
 '2060A>C',
 '2073A>C',
 '2074A>T',
 '2081T>C',
 '2082G>C',
 '2091A>C',
 '2096T>C',
 '2099T>C',
 '2100C>A',
 '2103A>C',
 '2106A>C',
 '2112A>C',
 '2120G>T',
 '2125C>A',
 '2127A>C',
 '2131A>T',
 '2132A>T',
 '2135A>T',
 '2147G>C',
 '2149G>T',
 '2153A>C',
 '2154A>T',
 '2157T>A',
 '2158T>C',
 '2163A>C',
 '2165C>A',
 '2172A>C',
 '2177T>C',
 '2178A>C',
 '2179A>C',
 '2180A>C',
 '2182G>C',
 '2188A>T',
 '2191A>T',
 '2192A>T',
 '2195A>C',
 '2196A>T',
 '2197G>T',
 '2198A>G',
 '2199A>T',
 '2204T>G',
 '2216A>T',
 '2217C>A',
 '2222T>G',
 '2225C>A',
 '2229A>T',
 '2230A>C',
 '2239A>C',
 '2246A>C',
 '2249G>C',
 '2251A>C',
 '2260A>C',
 '2261C>A',
 '2262C>A',
 '2263C>A',
 '2270A>T',
 '2273A>T',
 '2274A>C',
 '2280C>A',
 '2287T>G',
 '2295C>A',
 '2296T>G',
 '2311T>G',
 '2318A>T',
 '2321A>C',
 '2324T>G',
 '2325T>A',
 '2337A>C',
 '2342T>G',
 '2348A>T',
 '2353A>T',
 '2354A>G',
 '2355A>C',
 '2356A>C',
 '2358A>C',
 '2359C>A',
 '2363A>C',
 '2365T>A',
 '2399A>C',
 '2410T>C',
 '2411T>A',
 '2411T>C',
 '2416T>C',
 '2421G>C',
 '2421G>T',
 '2422T>A',
 '2422T>C',
 '2423C>A',
 '2424A>C',
 '2425A>T',
 '2425A>C',
 '2432A>C',
 '2434A>T',
 '2446A>T',
 '2453G>A',
 '2461A>C',
 '2469A>C',
 '2471G>T',
 '2478G>T',
 '2482A>C',
 '2486T>G',
 '2504A>C',
 '2512A>C',
 '2515T>A',
 '2517T>G',
 '2521A>C',
 '2524A>C',
 '2525C>G',
 '2526C>A',
 '2527A>C',
 '2527A>T',
 '2532T>C',
 '2532T>G',
 '2533A>T',
 '2535A>T',
 '2536G>T',
 '2538C>T',
 '2539A>T',
 '2541C>A',
 '2548C>T',
 '2552T>G',
 '2556A>T',
 '2561T>A',
 '2562T>A',
 '2565A>T',
 '2569C>A',
 '2572C>T',
 '2574G>T',
 '2576A>G',
 '2582A>T',
 '2584C>G',
 '2600A>T',
 '2609T>G',
 '2617A>T',
 '2617A>G',
 '2626T>A',
 '2634T>G',
 '2648T>G',
 '2652G>C',
 '2660T>G',
 '2664T>A',
 '2668A>C',
 '2669A>C',
 '2700G>T',
 '2700G>A',
 '2706A>G',
 '2710C>A',
 '2715A>C',
 '2724G>T',
 '2730A>C',
 '2732G>T',
 '2735G>T',
 '2741A>T',
 '2742T>A',
 '2743T>A',
 '2745A>T',
 '2746T>A',
 '2747T>G',
 '2748A>T',
 '2753A>T',
 '2754A>T',
 '2763T>G',
 '2767A>C',
 '2768A>C',
 '2773A>C',
 '2778T>C',
 '2780C>A',
 '2786T>G',
 '2792A>C',
 '2796G>T',
 '2799T>A',
 '2802A>C',
 '2803A>T',
 '2820A>T',
 '2827A>G',
 '2849G>T',
 '2850T>G',
 '2854T>C',
 '2875A>C',
 '2894T>G',
 '2898T>G',
 '2910A>G',
 '2918A>C',
 '2924T>A',
 '2930T>G',
 '2936T>G',
 '2945A>G',
 '2951A>T',
 '2972A>C',
 '2973T>G',
 '2974A>C',
 '2978T>A',
 '2984A>C',
 '2984A>T',
 '2999C>A',
 '3000A>T',
 '3000A>G',
 '3005A>T',
 '3006T>G',
 '3010G>C',
 '3011A>T',
 '3014G>T',
 '3016G>A',
 '3018A>T',
 '3022G>A',
 '3023C>G',
 '3024T>G',
 '3028A>G',
 '3029A>C',
 '3033T>G',
 '3037T>A',
 '3045A>C',
 '3049T>A',
 '3053A>C',
 '3062T>G',
 '3066C>G',
 '3081A>T',
 '3086T>G',
 '3087C>A',
 '3098T>A',
 '3100T>G',
 '3101A>C',
 '3109T>C',
 '3110C>A',
 '3113A>T',
 '3114T>G',
 '3115T>C',
 '3129A>C',
 '3145A>C',
 '3151A>G',
 '3151A>C',
 '3154T>A',
 '3157C>A',
 '3160A>C',
 '3161G>C',
 '3173G>T',
 '3184C>A',
 '3186T>G',
 '3197T>G',
 '3202T>G',
 '3232T>C',
 '3283G>A',
 '3303C>A',
 '3326T>G',
 '3363C>A',
 '3367A>C',
 '3380G>T',
 '3388C>A',
 '3398T>G',
 '3401A>C',
 '3422T>G',
 '3425T>G',
 '3425T>C',
 '3427G>T',
 '3429C>A',
 '3433T>C',
 '3437G>T',
 '3440T>G',
 '3449C>A',
 '3451T>C',
 '3458A>T',
 '3461C>A',
 '3462C>A',
 '3464T>A',
 '3465A>G',
 '3466A>C',
 '3472T>G',
 '3475A>C',
 '3475A>T',
 '3479A>C',
 '3486C>A',
 '3488T>G',
 '3489A>C',
 '3491A>C',
 '3492A>C',
 '3492A>T',
 '3499A>C',
 '3501A>C',
 '3503C>A',
 '3505A>C',
 '3506C>A',
 '3508A>C',
 '3509T>G',
 '3509T>A',
 '3509T>C',
 '3510C>T',
 '3511A>T',
 '3511A>C',
 '3514C>A',
 '3515T>A',
 '3515T>C',
 '3515T>G',
 '3517T>G',
 '3517T>A',
 '3517T>C',
 '3518A>C',
 '3519C>A',
 '3520A>C',
 '3521T>A',
 '3521T>G',
 '3521T>C',
 '3522C>T',
 '3524C>A',
 '3524C>T',
 '3526G>T',
 '3526G>C',
 '3531G>C',
 '3531G>T',
 '3532A>T',
 '3534C>A',
 '3535T>A',
 '3536T>G',
 '3537A>C',
 '3538G>T',
 '3538G>C',
 '3540T>C',
 '3541C>A',
 '3542T>G',
 '3542T>A',
 '3542T>C',
 '3544A>G',
 '3544A>C',
 '3545C>A',
 '3546C>A',
 '3547A>T',
 '3547A>C',
 '3548T>A',
 '3549C>A',
 '3550G>A',
 '3552T>A',
 '3552T>G',
 '3553C>A',
 '3554T>G',
 '3554T>A',
 '3554T>C',
 '3555T>A',
 '3557T>G',
 '3558A>C',
 '3558A>T',
 '3558A>G',
 '3559C>A',
 '3560T>G',
 '3560T>A',
 '3560T>C',
 '3561A>C',
 '3562T>G',
 '3562T>A',
 '3563G>T',
 '3564A>C',
 '3565A>T',
 '3567C>A',
 '3569C>A',
 '3571C>A',
 '3572T>G',
 '3572T>A',
 '3576C>A',
 '3577A>C',
 '3578T>G',
 '3579A>C',
 '3579A>T',
 '3580C>A',
 '3581C>A',
 '3583A>T',
 '3583A>C',
 '3584A>C',
 '3585C>A',
 '3587C>A',
 '3589C>A',
 '3589C>T',
 '3590T>G',
 '3590T>C',
 '3591G>T',
 '3592G>C',
 '3595A>C',
 '3596A>C',
 '3599T>A',
 '3599T>C',
 '3601A>C',
 '3605T>C',
 '3605T>G',
 '3606A>C',
 '3607G>C',
 '3608G>T',
 '3609C>G',
 '3609C>A',
 '3610C>A',
 '3611T>G',
 '3611T>A',
 '3613C>A',
 '3614T>A',
 '3614T>G',
 '3617T>G',
 '3618T>C',
 '3618T>G',
 '3619A>T',
 '3620T>A',
 '3620T>G',
 '3621T>G',
 '3623T>G',
 '3624A>T',
 '3624A>C',
 '3625G>T',
 '3626C>A',
 '3629C>A',
 '3631T>C',
 '3631T>A',
 '3632C>A',
 '3633T>G',
 '3633T>A',
 '3634A>C',
 '3635G>T',
 '3636C>A',
 '3638T>G',
 '3640G>C',
 '3640G>T',
 '3643G>T',
 '3644T>A',
 '3644T>G',
 '3645T>G',
 '3646T>G',
 '3647A>C',
 '3649T>A',
 '3652A>C',
 '3653T>C',
 '3653T>G',
 '3654C>A',
 '3656T>C',
 '3658T>A',
 '3658T>C',
 '3661T>G',
 '3661T>A',
 '3663A>G',
 '3663A>C',
 '3664G>T',
 '3664G>C',
 '3665G>C',
 '3665G>T',
 '3666G>C',
 '3667T>G',
 '3667T>A',
 '3667T>C',
 '3670G>T',
 '3671C>T',
 '3672A>T',
 '3672A>C',
 '3673T>A',
 '3673T>C',
 '3675A>C',
 '3676A>T',
 '3679T>C',
 '3680C>A',
 '3682A>G',
 '3682A>C',
 '3683A>T',
 '3685T>G',
 '3686A>C',
 '3692T>A',
 '3697G>T',
 '3698G>T',
 '3701C>A',
 '3702A>C',
 '3704T>A',
 '3704T>C',
 '3704T>G',
 '3713T>G',
 '3715G>T',
 '3715G>C',
 '3719A>C',
 '3719A>T',
 '3721A>C',
 '3723A>C',
 '3723A>T',
 '3724A>C',
 '3727T>A',
 '3729A>T',
 '3730T>A',
 '3730T>G',
 '3731A>C',
 '3732T>A',
 '3734A>T',
 '3737T>A',
 '3739A>T',
 '3739A>C',
 '3741C>A',
 '3741C>T',
 '3743T>G',
 '3743T>A',
 '3745G>C',
 '3747C>T',
 '3748A>C',
 '3748A>T',
 '3749T>A',
 '3749T>C',
 '3752T>G',
 '3759A>C',
 '3760T>A',
 '3760T>G',
 '3761C>A',
 '3762A>C',
 '3762A>T',
 '3763A>T',
 '3763A>C',
 '3765A>C',
 '3766T>G',
 '3767T>G',
 '3768A>C',
 '3769C>A',
 '3772A>C',
 '3774A>T',
 '3775A>C',
 '3776G>C',
 '3777T>A',
 '3777T>G',
 '3779G>T',
 '3781T>C',
 '3781T>G',
 '3784T>A',
 '3785T>G',
 '3785T>A',
 '3786T>G',
 '3786T>A',
 '3787A>T',
 '3787A>C',
 '3788A>T',
 '3788A>C',
 '3791T>C',
 '3791T>A',
 '3794C>A',
 '3796A>C',
 '3798C>A',
 '3800T>G',
 '3801T>G',
 '3802A>C',
 '3803T>G',
 '3807A>C',
 '3808A>C',
 '3810A>C',
 '3812A>C',
 '3812A>T',
 '3813A>C',
 '3814G>C',
 '3816A>C',
 '3818A>C',
 '3821T>C',
 '3823T>G',
 '3826T>G',
 '3827T>G',
 '3833T>G',
 '3834G>T',
 '3836C>A',
 '3837A>C',
 '3838T>A',
 '3846C>A',
 '3847T>G',
 '3847T>A',
 '3848T>G',
 '3849G>T',
 '3854T>G',
 '3855A>T',
 '3858A>C',
 '3859T>G',
 '3862T>C',
 '3866T>A',
 '3866T>G',
 '3868T>G',
 '3871A>C',
 '3873A>C',
 '3875T>G',
 '3876A>C',
 '3877G>T',
 '3881A>T',
 '3882G>C',
 '3883A>T',
 '3884C>A',
 '3886A>T',
 '3886A>C',
 '3887A>C',
 '3892A>G',
 '3892A>C',
 '3898T>A',
 '3899T>C',
 '3904C>A',
 '3905T>G',
 '3906T>C',
 '3906T>G',
 '3908C>G',
 '3912A>C',
 '3912A>T',
 '3913G>T',
 '3915G>C',
 '3919T>G',
 '3921C>T',
 '3923A>T',
 '3925C>G',
 '3926T>G',
 '3927A>C',
 '3933A>T',
 '3937T>G',
 '3940A>C',
 '3941A>C',
 '3943A>C',
 '3946G>A',
 '3948A>T',
 '3948A>C',
 '3949T>G',
 '3950A>T',
 '3950A>C',
 '3957A>C',
 '3960C>A',
 '3967G>A',
 '3975C>T',
 '3976T>G',
 '3980T>G',
 '3997A>T',
 '4012A>C',
 '4021A>T',
 '4024A>C',
 '4026A>C',
 '4027A>C',
 '4030T>G',
 '4033C>T',
 '4034T>G',
 '4035A>T',
 '4035A>G',
 '4035A>C',
 '4036G>T',
 '4037G>T',
 '4038A>T',
 '4042A>C',
 '4046A>C',
 '4048G>T',
 '4051G>A',
 '4053A>T',
 '4053A>C',
 '4055T>A',
 '4057T>A',
 '4061C>A',
 '4062T>A',
 '4063G>T',
 '4064A>T',
 '4065A>T',
 '4072A>C',
 '4094C>G',
 '4101T>A',
 '4105A>C',
 '4111C>T',
 '4129A>G',
 '4144T>G',
 '4678T>G',
 '4712C>A',
 '4714G>T',
 '4722A>C',
 '4726T>G',
 '4732A>T',
 '4779A>C',
 '4800T>C',
 '4806T>G',
 '4807T>C',
 '4815C>A',
 '4825C>A',
 '4826C>A',
 '4830G>T',
 '4831G>T',
 ...]

In [164]:
# build two <cell by variant tables>, one for each strand
total_coverage_variant_df = []
fwd_cell_variant_df, rev_cell_variant_df = [], []

In [166]:
total_coverage[2]

AAACCCACAAGAGCTG-1    0.0
AAACCCACACAGCCAC-1    3.0
AAACGAACAACGATCT-1    0.0
AAACGAAGTACCGCGT-1    0.0
AAACGAATCAATCTCT-1    0.0
                     ...
TTTGGAGGTGCAACGA-1    0.0
TTTGGTTAGTGGTCAG-1    0.0
TTTGGTTGTACGAAAT-1    0.0
TTTGTTGAGCACCAGA-1    0.0
TTTGTTGAGGCTTCCG-1    0.0
Name: 2, Length: 1256, dtype: float64

In [179]:
base_coverage_dict["A"][0][3].values

array([0, 0, 0, ..., 0, 0, 0])

In [167]:
for i, var in enumerate(variants):
    var_name = variant_names[i]
    pos, base = var[0], var[2]
    total_coverage_variant_df.append(total_coverage[pos])
    fwd_cell_variant_df.append(base_coverage_dict[base][0][pos].values)
    rev_cell_variant_df.append(base_coverage_dict[base][1][pos].values)

In [169]:
fwd_cell_variant_df

[array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 6., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 4., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([  9., 103.,  13., ...,  22.,  44.,  23.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([23., 95.,  5., ..., 24., 92., 22.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([1., 0., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 2., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([1., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 1., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([2., 0., 1., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([1., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 1., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 1., 0., 0.]),
 array([0., 2., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 1., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 2., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 1., 1.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([1., 1., 0., ..., 0., 1., 1.]),
 array([0., 3., 2., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([1., 0., 1., ..., 0., 1., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([1., 0., 0., ..., 0., 0., 0.]),
 array([0., 2., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([ 0., 17.,  4., ...,  0., 11.,  0.]),
 array([ 0., 28.,  0., ..., 11., 33.,  1.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([ 0., 77., 27., ...,  3., 40., 24.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 1., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 1., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),

In [170]:
total_coverage_variant_df = pd.DataFrame(np.array(total_coverage_variant_df).T, index=cell_barcodes, columns=variant_names)

In [171]:
total_coverage_variant_df

,34G>T,39C>A,45A>C,46T>G,49A>C,51T>A,52T>G,58T>G,65T>G,73A>G,...,16534A>C,16534A>G,16535G>T,16537C>A,16538C>A,16542C>T,16543G>T,16547C>A,16558G>T,16561A>C
AAACCCACAAGAGCTG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACCCACACAGCCAC-1,6.0,8.0,10.0,10.0,11.0,12.0,12.0,13.0,14.0,15.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
AAACGAACAACGATCT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAAGTACCGCGT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAATCAATCTCT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGAGGTGCAACGA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGGTTAGTGGTCAG-1,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,...,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0
TTTGGTTGTACGAAAT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGAGCACCAGA-1,0.0,0.0,1.0,1.0,1.0,1.0,1.0,5.0,6.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGAGGCTTCCG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [172]:
fwd_cell_variant_df = pd.DataFrame(np.array(fwd_cell_variant_df).T, index=cell_barcodes, columns=variant_names)
rev_cell_variant_df = pd.DataFrame(np.array(rev_cell_variant_df).T, index=cell_barcodes, columns=variant_names)

In [173]:
all_cell_variant_df = fwd_cell_variant_df + rev_cell_variant_df

In [174]:
all_cell_variant_df

,34G>T,39C>A,45A>C,46T>G,49A>C,51T>A,52T>G,58T>G,65T>G,73A>G,...,16534A>C,16534A>G,16535G>T,16537C>A,16538C>A,16542C>T,16543G>T,16547C>A,16558G>T,16561A>C
AAACCCACAAGAGCTG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACCCACACAGCCAC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAACAACGATCT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAAGTACCGCGT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAATCAATCTCT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGAGGTGCAACGA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGGTTAGTGGTCAG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGGTTGTACGAAAT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGAGCACCAGA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGAGGCTTCCG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [180]:
heteroplasmic_df = all_cell_variant_df / total_coverage_variant_df

In [181]:
heteroplasmic_df

,34G>T,39C>A,45A>C,46T>G,49A>C,51T>A,52T>G,58T>G,65T>G,73A>G,...,16534A>C,16534A>G,16535G>T,16537C>A,16538C>A,16542C>T,16543G>T,16547C>A,16558G>T,16561A>C
AAACCCACAAGAGCTG-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AAACCCACACAGCCAC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAACAACGATCT-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AAACGAAGTACCGCGT-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AAACGAATCAATCTCT-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGAGGTGCAACGA-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGGTTAGTGGTCAG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGGTTGTACGAAAT-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGTTGAGCACCAGA-1,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGTTGAGGCTTCCG-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [182]:
mask_idx = (fwd_cell_variant_df + rev_cell_variant_df) == 0  # set 0 on both strands to nan to exclude from correlation calculation
fwd_cell_variant_df[mask_idx] = np.nan
rev_cell_variant_df[mask_idx] = np.nan

In [183]:
fwd_cell_variant_df

,34G>T,39C>A,45A>C,46T>G,49A>C,51T>A,52T>G,58T>G,65T>G,73A>G,...,16534A>C,16534A>G,16535G>T,16537C>A,16538C>A,16542C>T,16543G>T,16547C>A,16558G>T,16561A>C
AAACCCACAAGAGCTG-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AAACCCACACAGCCAC-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AAACGAACAACGATCT-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AAACGAAGTACCGCGT-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AAACGAATCAATCTCT-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGAGGTGCAACGA-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGGTTAGTGGTCAG-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGGTTGTACGAAAT-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGTTGAGCACCAGA-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGTTGAGGCTTCCG-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [184]:
variant_strand_corr = fwd_cell_variant_df.corrwith(rev_cell_variant_df).round(3)

In [185]:
variant_strand_corr

34G>T      -1.0
39C>A      -1.0
45A>C      -1.0
46T>G      -1.0
49A>C      -1.0
           ...
16542C>T   -1.0
16543G>T   -1.0
16547C>A   -1.0
16558G>T   -1.0
16561A>C   -1.0
Length: 6231, dtype: float64

In [187]:
variant_mean = all_cell_variant_df.sum() / total_coverage_variant_df.sum()
variant_var = heteroplasmic_df.var()

In [188]:
variant_vmr = variant_var / (variant_mean + 0.00000000001)

In [189]:
variant_vmr

34G>T       0.721038
39C>A       0.036336
45A>C       0.105543
46T>G       0.080974
49A>C       0.022477
              ...
16542C>T    0.078556
16543G>T    0.025245
16547C>A    0.038654
16558G>T    1.481099
16561A>C    2.216960
Length: 6231, dtype: float64

In [190]:
variants

[(34, 'G', 'T'),
 (39, 'C', 'A'),
 (45, 'A', 'C'),
 (46, 'T', 'G'),
 (49, 'A', 'C'),
 (51, 'T', 'A'),
 (52, 'T', 'G'),
 (58, 'T', 'G'),
 (65, 'T', 'G'),
 (73, 'A', 'G'),
 (75, 'G', 'A'),
 (76, 'C', 'T'),
 (76, 'C', 'A'),
 (79, 'G', 'T'),
 (81, 'G', 'T'),
 (82, 'A', 'G'),
 (91, 'C', 'T'),
 (96, 'C', 'T'),
 (96, 'C', 'A'),
 (97, 'G', 'A'),
 (98, 'C', 'A'),
 (106, 'G', 'A'),
 (110, 'C', 'T'),
 (110, 'C', 'A'),
 (117, 'T', 'G'),
 (121, 'G', 'A'),
 (125, 'T', 'G'),
 (134, 'T', 'G'),
 (137, 'A', 'T'),
 (138, 'T', 'C'),
 (145, 'C', 'A'),
 (149, 'T', 'G'),
 (150, 'C', 'T'),
 (154, 'T', 'G'),
 (157, 'T', 'G'),
 (163, 'G', 'A'),
 (169, 'A', 'C'),
 (172, 'T', 'G'),
 (173, 'T', 'C'),
 (175, 'A', 'C'),
 (182, 'C', 'T'),
 (183, 'A', 'T'),
 (183, 'A', 'G'),
 (187, 'G', 'T'),
 (189, 'A', 'C'),
 (195, 'T', 'G'),
 (199, 'T', 'A'),
 (201, 'A', 'T'),
 (215, 'A', 'T'),
 (219, 'A', 'T'),
 (221, 'G', 'T'),
 (222, 'C', 'A'),
 (225, 'G', 'T'),
 (227, 'A', 'G'),
 (229, 'G', 'A'),
 (229, 'G', 'T'),
 (230, 'A', 'C'),
 (237, 'A', 'G'),
 (237, 'A', 'T'),
 (238, 'A', 'C'),
 (239, 'T', 'G'),
 (240, 'A', 'G'),
 (242, 'C', 'A'),
 (248, 'A', 'G'),
 (249, 'A', 'C'),
 (254, 'T', 'A'),
 (257, 'A', 'G'),
 (259, 'A', 'C'),
 (263, 'A', 'T'),
 (263, 'A', 'G'),
 (264, 'C', 'A'),
 (265, 'T', 'G'),
 (266, 'T', 'C'),
 (269, 'C', 'A'),
 (270, 'A', 'C'),
 (272, 'A', 'C'),
 (274, 'A', 'C'),
 (276, 'A', 'C'),
 (278, 'A', 'C'),
 (279, 'T', 'G'),
 (280, 'C', 'G'),
 (282, 'T', 'G'),
 (283, 'A', 'C'),
 (284, 'A', 'C'),
 (286, 'A', 'C'),
 (287, 'A', 'C'),
 (288, 'A', 'C'),
 (289, 'A', 'C'),
 (290, 'A', 'T'),
 (291, 'A', 'T'),
 (292, 'T', 'A'),
 (292, 'T', 'G'),
 (293, 'T', 'G'),
 (297, 'A', 'T'),
 (297, 'A', 'C'),
 (298, 'C', 'A'),
 (300, 'A', 'G'),
 (300, 'A', 'C'),
 (301, 'A', 'G'),
 (301, 'A', 'T'),
 (301, 'A', 'C'),
 (302, 'A', 'C'),
 (302, 'A', 'T'),
 (303, 'C', 'A'),
 (306, 'C', 'G'),
 (308, 'C', 'T'),
 (309, 'C', 'T'),
 (310, 'T', 'A'),
 (310, 'T', 'G'),
 (310, 'T', 'C'),
 (311, 'C', 'A'),
 (313, 'C', 'G'),
 (314, 'C', 'G'),
 (318, 'T', 'G'),
 (321, 'T', 'G'),
 (322, 'G', 'T'),
 (326, 'A', 'C'),
 (327, 'C', 'A'),
 (328, 'A', 'C'),
 (331, 'A', 'T'),
 (333, 'T', 'A'),
 (333, 'T', 'G'),
 (334, 'T', 'G'),
 (337, 'A', 'C'),
 (338, 'C', 'A'),
 (339, 'A', 'C'),
 (341, 'A', 'G'),
 (341, 'A', 'C'),
 (342, 'T', 'A'),
 (342, 'T', 'G'),
 (343, 'C', 'A'),
 (346, 'T', 'A'),
 (349, 'C', 'A'),
 (350, 'A', 'G'),
 (351, 'A', 'G'),
 (352, 'A', 'C'),
 (353, 'C', 'A'),
 (354, 'C', 'A'),
 (356, 'C', 'A'),
 (357, 'A', 'C'),
 (362, 'C', 'A'),
 (364, 'A', 'C'),
 (365, 'A', 'G'),
 (366, 'G', 'T'),
 (368, 'A', 'C'),
 (369, 'C', 'A'),
 (370, 'C', 'A'),
 (371, 'C', 'T'),
 (372, 'T', 'A'),
 (372, 'T', 'G'),
 (375, 'C', 'A'),
 (376, 'A', 'T'),
 (377, 'C', 'A'),
 (378, 'C', 'A'),
 (378, 'C', 'T'),
 (379, 'A', 'G'),
 (380, 'G', 'C'),
 (381, 'C', 'T'),
 (382, 'C', 'T'),
 (383, 'T', 'C'),
 (383, 'T', 'G'),
 (383, 'T', 'A'),
 (384, 'A', 'C'),
 (386, 'C', 'A'),
 (387, 'C', 'A'),
 (387, 'C', 'G'),
 (388, 'A', 'G'),
 (388, 'A', 'C'),
 (389, 'G', 'T'),
 (390, 'A', 'C'),
 (391, 'T', 'A'),
 (391, 'T', 'C'),
 (391, 'T', 'G'),
 (392, 'T', 'G'),
 (392, 'T', 'A'),
 (393, 'T', 'C'),
 (394, 'C', 'A'),
 (395, 'A', 'G'),
 (396, 'A', 'T'),
 (396, 'A', 'G'),
 (398, 'T', 'G'),
 (398, 'T', 'A'),
 (399, 'T', 'G'),
 (400, 'T', 'A'),
 (400, 'T', 'C'),
 (400, 'T', 'G'),
 (401, 'T', 'G'),
 (402, 'A', 'C'),
 (402, 'A', 'G'),
 (404, 'C', 'A'),
 (405, 'T', 'C'),
 (405, 'T', 'G'),
 (406, 'T', 'A'),
 (406, 'T', 'G'),
 (408, 'T', 'C'),
 (409, 'G', 'C'),
 (411, 'C', 'A'),
 (475, 'A', 'C'),
 (503, 'A', 'C'),
 (505, 'C', 'A'),
 (531, 'T', 'G'),
 (687, 'G', 'T'),
 (697, 'G', 'T'),
 (745, 'A', 'C'),
 (746, 'A', 'C'),
 (747, 'A', 'C'),
 (750, 'A', 'G'),
 (773, 'T', 'C'),
 (810, 'G', 'T'),
 (812, 'A', 'T'),
 (831, 'T', 'G'),
 (832, 'T', 'G'),
 (839, 'A', 'C'),
 (840, 'A', 'C'),
 (844, 'A', 'C'),
 (871, 'A', 'C'),
 (885, 'T', 'A'),
 (888, 'T', 'G'),
 (890, 'C', 'T'),
 (892, 'A', 'G'),
 (903, 'T', 'A'),
 (905, 'A', 'C'),
 (913, 'A', 'T'),
 (914, 'A', 'C'),
 (921, 'T', 'A'),
 (923, 'A', 'G'),
 (924, 'A', 'C'),
 (925, 'T', 'G'),
 (937, 'T', 'A'),
 (938, 'A', 'T'),
 (940, 'A', 'C'),
 (942, 'A', 'C'),
 (949, 'T', 'C'),
 (953, 'T', 'A'),
 (955, 'A', 'T'),
 (957, 'C', 'G'),
 (960, 'C', 'T'),
 (961, 'T', 'C'),
 (966, 'A', 'C'),
 (967, 'A', 'C'),
 (969, 'A', 'C'),
 (970, 'A', 'C'),
 (972, 'G', 'T'),
 (976, 'A', 'C'),
 (988, 'G', 'T'),
 (991, 'G', 'T'),
 (994, 'A', 'G'),
 (995, 'A', 'T'),
 (997, 'A', 'C'),
 (999, 'C', 'A'),
 (1004, 'G', 'T'),
 (1005, 'T', 'A'),
 (1007, 'G', 'T'),
 (1010, 'A', 'T'),
 (1012, 'A', 'T'),
 (1014, 'A', 'C'),
 (1015, 'A', 'C'),
 (1017, 'A', 'C'),
 (1019, 'A', 'T'),
 (1028, 'G', 'C'),
 (1030, 'G', 'T'),
 (1032, 'C', 'A'),
 (1039, 'A', 'C'),
 (1041, 'A', 'C'),
 (1047, 'A', 'C'),
 (1055, 'T', 'G'),
 (1069, 'A', 'C'),
 (1085, 'C', 'A'),
 (1092, 'G', 'C'),
 (1096, 'A', 'C'),
 (1256, 'A', 'T'),
 (1259, 'T', 'G'),
 (1261, 'C', 'T'),
 (1268, 'C', 'A'),
 (1273, 'G', 'T'),
 (1273, 'G', 'C'),
 (1274, 'C', 'A'),
 (1276, 'A', 'C'),
 (1282, 'G', 'T'),
 (1289, 'G', 'T'),
 (1292, 'A', 'T'),
 (1294, 'A', 'T'),
 (1299, 'A', 'T'),
 (1299, 'A', 'G'),
 (1301, 'G', 'T'),
 (1303, 'G', 'C'),
 (1305, 'A', 'T'),
 (1306, 'A', 'T'),
 (1308, 'T', 'A'),
 (1313, 'A', 'C'),
 (1359, 'T', 'C'),
 (1361, 'G', 'C'),
 (1373, 'T', 'C'),
 (1398, 'T', 'A'),
 (1403, 'A', 'C'),
 (1404, 'A', 'T'),
 (1407, 'T', 'C'),
 (1438, 'A', 'G'),
 (1502, 'A', 'C'),
 (1527, 'A', 'G'),
 (1728, 'T', 'A'),
 (1830, 'G', 'T'),
 (1856, 'A', 'C'),
 (1859, 'A', 'T'),
 (1878, 'T', 'C'),
 (1878, 'T', 'G'),
 (1884, 'G', 'T'),
 (1888, 'G', 'T'),
 (1898, 'A', 'T'),
 (1903, 'C', 'A'),
 (1909, 'A', 'C'),
 (1916, 'G', 'T'),
 (1938, 'A', 'C'),
 (1952, 'T', 'G'),
 (1963, 'A', 'T'),
 (1969, 'G', 'T'),
 (1986, 'A', 'G'),
 (1987, 'G', 'T'),
 (1988, 'G', 'C'),
 (1990, 'G', 'C'),
 (1995, 'A', 'C'),
 (1999, 'A', 'T'),
 (2003, 'A', 'C'),
 (2007, 'T', 'C'),
 (2018, 'G', 'T'),
 (2020, 'T', 'G'),
 (2020, 'T', 'A'),
 (2034, 'A', 'C'),
 (2034, 'A', 'G'),
 (2035, 'T', 'A'),
 (2039, 'A', 'T'),
 (2045, 'A', 'G'),
 (2046, 'C', 'T'),
 (2052, 'A', 'T'),
 (2054, 'T', 'G'),
 (2055, 'T', 'G'),
 (2058, 'C', 'A'),
 (2060, 'A', 'C'),
 (2073, 'A', 'C'),
 (2074, 'A', 'T'),
 (2081, 'T', 'C'),
 (2082, 'G', 'C'),
 (2091, 'A', 'C'),
 (2096, 'T', 'C'),
 (2099, 'T', 'C'),
 (2100, 'C', 'A'),
 (2103, 'A', 'C'),
 (2106, 'A', 'C'),
 (2112, 'A', 'C'),
 (2120, 'G', 'T'),
 (2125, 'C', 'A'),
 (2127, 'A', 'C'),
 (2131, 'A', 'T'),
 (2132, 'A', 'T'),
 (2135, 'A', 'T'),
 (2147, 'G', 'C'),
 (2149, 'G', 'T'),
 (2153, 'A', 'C'),
 (2154, 'A', 'T'),
 (2157, 'T', 'A'),
 (2158, 'T', 'C'),
 (2163, 'A', 'C'),
 (2165, 'C', 'A'),
 (2172, 'A', 'C'),
 (2177, 'T', 'C'),
 (2178, 'A', 'C'),
 (2179, 'A', 'C'),
 (2180, 'A', 'C'),
 (2182, 'G', 'C'),
 (2188, 'A', 'T'),
 (2191, 'A', 'T'),
 (2192, 'A', 'T'),
 (2195, 'A', 'C'),
 (2196, 'A', 'T'),
 (2197, 'G', 'T'),
 (2198, 'A', 'G'),
 (2199, 'A', 'T'),
 (2204, 'T', 'G'),
 (2216, 'A', 'T'),
 (2217, 'C', 'A'),
 (2222, 'T', 'G'),
 (2225, 'C', 'A'),
 (2229, 'A', 'T'),
 (2230, 'A', 'C'),
 (2239, 'A', 'C'),
 (2246, 'A', 'C'),
 (2249, 'G', 'C'),
 (2251, 'A', 'C'),
 (2260, 'A', 'C'),
 (2261, 'C', 'A'),
 (2262, 'C', 'A'),
 (2263, 'C', 'A'),
 (2270, 'A', 'T'),
 (2273, 'A', 'T'),
 (2274, 'A', 'C'),
 (2280, 'C', 'A'),
 (2287, 'T', 'G'),
 (2295, 'C', 'A'),
 (2296, 'T', 'G'),
 (2311, 'T', 'G'),
 (2318, 'A', 'T'),
 (2321, 'A', 'C'),
 (2324, 'T', 'G'),
 (2325, 'T', 'A'),
 (2337, 'A', 'C'),
 (2342, 'T', 'G'),
 (2348, 'A', 'T'),
 (2353, 'A', 'T'),
 (2354, 'A', 'G'),
 (2355, 'A', 'C'),
 (2356, 'A', 'C'),
 (2358, 'A', 'C'),
 (2359, 'C', 'A'),
 (2363, 'A', 'C'),
 (2365, 'T', 'A'),
 (2399, 'A', 'C'),
 (2410, 'T', 'C'),
 (2411, 'T', 'A'),
 (2411, 'T', 'C'),
 (2416, 'T', 'C'),
 (2421, 'G', 'C'),
 (2421, 'G', 'T'),
 (2422, 'T', 'A'),
 (2422, 'T', 'C'),
 (2423, 'C', 'A'),
 (2424, 'A', 'C'),
 (2425, 'A', 'T'),
 (2425, 'A', 'C'),
 (2432, 'A', 'C'),
 (2434, 'A', 'T'),
 (2446, 'A', 'T'),
 (2453, 'G', 'A'),
 (2461, 'A', 'C'),
 (2469, 'A', 'C'),
 (2471, 'G', 'T'),
 (2478, 'G', 'T'),
 (2482, 'A', 'C'),
 (2486, 'T', 'G'),
 (2504, 'A', 'C'),
 (2512, 'A', 'C'),
 (2515, 'T', 'A'),
 (2517, 'T', 'G'),
 (2521, 'A', 'C'),
 (2524, 'A', 'C'),
 (2525, 'C', 'G'),
 (2526, 'C', 'A'),
 (2527, 'A', 'C'),
 (2527, 'A', 'T'),
 (2532, 'T', 'C'),
 (2532, 'T', 'G'),
 (2533, 'A', 'T'),
 (2535, 'A', 'T'),
 (2536, 'G', 'T'),
 (2538, 'C', 'T'),
 (2539, 'A', 'T'),
 (2541, 'C', 'A'),
 (2548, 'C', 'T'),
 (2552, 'T', 'G'),
 (2556, 'A', 'T'),
 (2561, 'T', 'A'),
 (2562, 'T', 'A'),
 (2565, 'A', 'T'),
 (2569, 'C', 'A'),
 (2572, 'C', 'T'),
 (2574, 'G', 'T'),
 (2576, 'A', 'G'),
 (2582, 'A', 'T'),
 (2584, 'C', 'G'),
 (2600, 'A', 'T'),
 (2609, 'T', 'G'),
 (2617, 'A', 'T'),
 (2617, 'A', 'G'),
 (2626, 'T', 'A'),
 (2634, 'T', 'G'),
 (2648, 'T', 'G'),
 (2652, 'G', 'C'),
 (2660, 'T', 'G'),
 (2664, 'T', 'A'),
 (2668, 'A', 'C'),
 (2669, 'A', 'C'),
 (2700, 'G', 'T'),
 (2700, 'G', 'A'),
 (2706, 'A', 'G'),
 (2710, 'C', 'A'),
 (2715, 'A', 'C'),
 (2724, 'G', 'T'),
 (2730, 'A', 'C'),
 (2732, 'G', 'T'),
 (2735, 'G', 'T'),
 (2741, 'A', 'T'),
 (2742, 'T', 'A'),
 (2743, 'T', 'A'),
 (2745, 'A', 'T'),
 (2746, 'T', 'A'),
 (2747, 'T', 'G'),
 (2748, 'A', 'T'),
 (2753, 'A', 'T'),
 (2754, 'A', 'T'),
 (2763, 'T', 'G'),
 (2767, 'A', 'C'),
 (2768, 'A', 'C'),
 (2773, 'A', 'C'),
 (2778, 'T', 'C'),
 (2780, 'C', 'A'),
 (2786, 'T', 'G'),
 (2792, 'A', 'C'),
 (2796, 'G', 'T'),
 (2799, 'T', 'A'),
 (2802, 'A', 'C'),
 (2803, 'A', 'T'),
 (2820, 'A', 'T'),
 (2827, 'A', 'G'),
 (2849, 'G', 'T'),
 (2850, 'T', 'G'),
 (2854, 'T', 'C'),
 (2875, 'A', 'C'),
 (2894, 'T', 'G'),
 (2898, 'T', 'G'),
 (2910, 'A', 'G'),
 (2918, 'A', 'C'),
 (2924, 'T', 'A'),
 (2930, 'T', 'G'),
 (2936, 'T', 'G'),
 (2945, 'A', 'G'),
 (2951, 'A', 'T'),
 (2972, 'A', 'C'),
 (2973, 'T', 'G'),
 (2974, 'A', 'C'),
 (2978, 'T', 'A'),
 (2984, 'A', 'C'),
 (2984, 'A', 'T'),
 (2999, 'C', 'A'),
 (3000, 'A', 'T'),
 (3000, 'A', 'G'),
 (3005, 'A', 'T'),
 (3006, 'T', 'G'),
 (3010, 'G', 'C'),
 (3011, 'A', 'T'),
 (3014, 'G', 'T'),
 (3016, 'G', 'A'),
 (3018, 'A', 'T'),
 (3022, 'G', 'A'),
 (3023, 'C', 'G'),
 (3024, 'T', 'G'),
 (3028, 'A', 'G'),
 (3029, 'A', 'C'),
 (3033, 'T', 'G'),
 (3037, 'T', 'A'),
 (3045, 'A', 'C'),
 (3049, 'T', 'A'),
 (3053, 'A', 'C'),
 (3062, 'T', 'G'),
 (3066, 'C', 'G'),
 (3081, 'A', 'T'),
 (3086, 'T', 'G'),
 (3087, 'C', 'A'),
 (3098, 'T', 'A'),
 (3100, 'T', 'G'),
 (3101, 'A', 'C'),
 (3109, 'T', 'C'),
 (3110, 'C', 'A'),
 (3113, 'A', 'T'),
 (3114, 'T', 'G'),
 (3115, 'T', 'C'),
 (3129, 'A', 'C'),
 (3145, 'A', 'C'),
 (3151, 'A', 'G'),
 (3151, 'A', 'C'),
 (3154, 'T', 'A'),
 (3157, 'C', 'A'),
 (3160, 'A', 'C'),
 (3161, 'G', 'C'),
 (3173, 'G', 'T'),
 (3184, 'C', 'A'),
 (3186, 'T', 'G'),
 (3197, 'T', 'G'),
 (3202, 'T', 'G'),
 (3232, 'T', 'C'),
 (3283, 'G', 'A'),
 (3303, 'C', 'A'),
 (3326, 'T', 'G'),
 (3363, 'C', 'A'),
 (3367, 'A', 'C'),
 (3380, 'G', 'T'),
 (3388, 'C', 'A'),
 (3398, 'T', 'G'),
 (3401, 'A', 'C'),
 (3422, 'T', 'G'),
 (3425, 'T', 'G'),
 (3425, 'T', 'C'),
 (3427, 'G', 'T'),
 (3429, 'C', 'A'),
 (3433, 'T', 'C'),
 (3437, 'G', 'T'),
 (3440, 'T', 'G'),
 (3449, 'C', 'A'),
 (3451, 'T', 'C'),
 (3458, 'A', 'T'),
 (3461, 'C', 'A'),
 (3462, 'C', 'A'),
 (3464, 'T', 'A'),
 (3465, 'A', 'G'),
 (3466, 'A', 'C'),
 (3472, 'T', 'G'),
 (3475, 'A', 'C'),
 (3475, 'A', 'T'),
 (3479, 'A', 'C'),
 (3486, 'C', 'A'),
 (3488, 'T', 'G'),
 (3489, 'A', 'C'),
 (3491, 'A', 'C'),
 (3492, 'A', 'C'),
 (3492, 'A', 'T'),
 (3499, 'A', 'C'),
 (3501, 'A', 'C'),
 (3503, 'C', 'A'),
 (3505, 'A', 'C'),
 (3506, 'C', 'A'),
 (3508, 'A', 'C'),
 (3509, 'T', 'G'),
 (3509, 'T', 'A'),
 (3509, 'T', 'C'),
 (3510, 'C', 'T'),
 (3511, 'A', 'T'),
 (3511, 'A', 'C'),
 (3514, 'C', 'A'),
 (3515, 'T', 'A'),
 (3515, 'T', 'C'),
 (3515, 'T', 'G'),
 (3517, 'T', 'G'),
 (3517, 'T', 'A'),
 (3517, 'T', 'C'),
 (3518, 'A', 'C'),
 (3519, 'C', 'A'),
 (3520, 'A', 'C'),
 (3521, 'T', 'A'),
 (3521, 'T', 'G'),
 (3521, 'T', 'C'),
 (3522, 'C', 'T'),
 (3524, 'C', 'A'),
 (3524, 'C', 'T'),
 (3526, 'G', 'T'),
 (3526, 'G', 'C'),
 (3531, 'G', 'C'),
 (3531, 'G', 'T'),
 (3532, 'A', 'T'),
 (3534, 'C', 'A'),
 (3535, 'T', 'A'),
 (3536, 'T', 'G'),
 (3537, 'A', 'C'),
 (3538, 'G', 'T'),
 (3538, 'G', 'C'),
 (3540, 'T', 'C'),
 (3541, 'C', 'A'),
 (3542, 'T', 'G'),
 (3542, 'T', 'A'),
 (3542, 'T', 'C'),
 (3544, 'A', 'G'),
 (3544, 'A', 'C'),
 (3545, 'C', 'A'),
 (3546, 'C', 'A'),
 (3547, 'A', 'T'),
 (3547, 'A', 'C'),
 (3548, 'T', 'A'),
 (3549, 'C', 'A'),
 (3550, 'G', 'A'),
 (3552, 'T', 'A'),
 (3552, 'T', 'G'),
 (3553, 'C', 'A'),
 (3554, 'T', 'G'),
 (3554, 'T', 'A'),
 (3554, 'T', 'C'),
 (3555, 'T', 'A'),
 (3557, 'T', 'G'),
 (3558, 'A', 'C'),
 (3558, 'A', 'T'),
 (3558, 'A', 'G'),
 (3559, 'C', 'A'),
 (3560, 'T', 'G'),
 (3560, 'T', 'A'),
 (3560, 'T', 'C'),
 (3561, 'A', 'C'),
 (3562, 'T', 'G'),
 (3562, 'T', 'A'),
 (3563, 'G', 'T'),
 (3564, 'A', 'C'),
 (3565, 'A', 'T'),
 (3567, 'C', 'A'),
 (3569, 'C', 'A'),
 (3571, 'C', 'A'),
 (3572, 'T', 'G'),
 (3572, 'T', 'A'),
 (3576, 'C', 'A'),
 (3577, 'A', 'C'),
 (3578, 'T', 'G'),
 (3579, 'A', 'C'),
 (3579, 'A', 'T'),
 (3580, 'C', 'A'),
 (3581, 'C', 'A'),
 (3583, 'A', 'T'),
 (3583, 'A', 'C'),
 (3584, 'A', 'C'),
 (3585, 'C', 'A'),
 (3587, 'C', 'A'),
 (3589, 'C', 'A'),
 (3589, 'C', 'T'),
 (3590, 'T', 'G'),
 (3590, 'T', 'C'),
 (3591, 'G', 'T'),
 (3592, 'G', 'C'),
 (3595, 'A', 'C'),
 (3596, 'A', 'C'),
 (3599, 'T', 'A'),
 (3599, 'T', 'C'),
 (3601, 'A', 'C'),
 (3605, 'T', 'C'),
 (3605, 'T', 'G'),
 (3606, 'A', 'C'),
 (3607, 'G', 'C'),
 (3608, 'G', 'T'),
 (3609, 'C', 'G'),
 (3609, 'C', 'A'),
 (3610, 'C', 'A'),
 (3611, 'T', 'G'),
 (3611, 'T', 'A'),
 (3613, 'C', 'A'),
 (3614, 'T', 'A'),
 (3614, 'T', 'G'),
 (3617, 'T', 'G'),
 (3618, 'T', 'C'),
 (3618, 'T', 'G'),
 (3619, 'A', 'T'),
 (3620, 'T', 'A'),
 (3620, 'T', 'G'),
 (3621, 'T', 'G'),
 (3623, 'T', 'G'),
 (3624, 'A', 'T'),
 (3624, 'A', 'C'),
 (3625, 'G', 'T'),
 (3626, 'C', 'A'),
 (3629, 'C', 'A'),
 (3631, 'T', 'C'),
 (3631, 'T', 'A'),
 (3632, 'C', 'A'),
 (3633, 'T', 'G'),
 (3633, 'T', 'A'),
 (3634, 'A', 'C'),
 (3635, 'G', 'T'),
 (3636, 'C', 'A'),
 (3638, 'T', 'G'),
 (3640, 'G', 'C'),
 (3640, 'G', 'T'),
 (3643, 'G', 'T'),
 (3644, 'T', 'A'),
 (3644, 'T', 'G'),
 (3645, 'T', 'G'),
 (3646, 'T', 'G'),
 (3647, 'A', 'C'),
 (3649, 'T', 'A'),
 (3652, 'A', 'C'),
 (3653, 'T', 'C'),
 (3653, 'T', 'G'),
 (3654, 'C', 'A'),
 (3656, 'T', 'C'),
 (3658, 'T', 'A'),
 (3658, 'T', 'C'),
 (3661, 'T', 'G'),
 (3661, 'T', 'A'),
 (3663, 'A', 'G'),
 (3663, 'A', 'C'),
 (3664, 'G', 'T'),
 (3664, 'G', 'C'),
 (3665, 'G', 'C'),
 (3665, 'G', 'T'),
 (3666, 'G', 'C'),
 (3667, 'T', 'G'),
 (3667, 'T', 'A'),
 (3667, 'T', 'C'),
 (3670, 'G', 'T'),
 (3671, 'C', 'T'),
 (3672, 'A', 'T'),
 (3672, 'A', 'C'),
 (3673, 'T', 'A'),
 (3673, 'T', 'C'),
 (3675, 'A', 'C'),
 (3676, 'A', 'T'),
 (3679, 'T', 'C'),
 (3680, 'C', 'A'),
 (3682, 'A', 'G'),
 (3682, 'A', 'C'),
 (3683, 'A', 'T'),
 (3685, 'T', 'G'),
 (3686, 'A', 'C'),
 (3692, 'T', 'A'),
 (3697, 'G', 'T'),
 (3698, 'G', 'T'),
 (3701, 'C', 'A'),
 (3702, 'A', 'C'),
 (3704, 'T', 'A'),
 (3704, 'T', 'C'),
 (3704, 'T', 'G'),
 (3713, 'T', 'G'),
 (3715, 'G', 'T'),
 (3715, 'G', 'C'),
 (3719, 'A', 'C'),
 (3719, 'A', 'T'),
 (3721, 'A', 'C'),
 (3723, 'A', 'C'),
 (3723, 'A', 'T'),
 (3724, 'A', 'C'),
 (3727, 'T', 'A'),
 (3729, 'A', 'T'),
 (3730, 'T', 'A'),
 (3730, 'T', 'G'),
 (3731, 'A', 'C'),
 (3732, 'T', 'A'),
 (3734, 'A', 'T'),
 (3737, 'T', 'A'),
 (3739, 'A', 'T'),
 (3739, 'A', 'C'),
 (3741, 'C', 'A'),
 (3741, 'C', 'T'),
 (3743, 'T', 'G'),
 (3743, 'T', 'A'),
 (3745, 'G', 'C'),
 (3747, 'C', 'T'),
 (3748, 'A', 'C'),
 (3748, 'A', 'T'),
 (3749, 'T', 'A'),
 (3749, 'T', 'C'),
 (3752, 'T', 'G'),
 (3759, 'A', 'C'),
 (3760, 'T', 'A'),
 (3760, 'T', 'G'),
 (3761, 'C', 'A'),
 (3762, 'A', 'C'),
 (3762, 'A', 'T'),
 (3763, 'A', 'T'),
 (3763, 'A', 'C'),
 (3765, 'A', 'C'),
 (3766, 'T', 'G'),
 (3767, 'T', 'G'),
 (3768, 'A', 'C'),
 (3769, 'C', 'A'),
 (3772, 'A', 'C'),
 (3774, 'A', 'T'),
 (3775, 'A', 'C'),
 (3776, 'G', 'C'),
 (3777, 'T', 'A'),
 (3777, 'T', 'G'),
 (3779, 'G', 'T'),
 (3781, 'T', 'C'),
 (3781, 'T', 'G'),
 (3784, 'T', 'A'),
 (3785, 'T', 'G'),
 (3785, 'T', 'A'),
 (3786, 'T', 'G'),
 (3786, 'T', 'A'),
 (3787, 'A', 'T'),
 (3787, 'A', 'C'),
 (3788, 'A', 'T'),
 (3788, 'A', 'C'),
 (3791, 'T', 'C'),
 (3791, 'T', 'A'),
 (3794, 'C', 'A'),
 (3796, 'A', 'C'),
 (3798, 'C', 'A'),
 (3800, 'T', 'G'),
 (3801, 'T', 'G'),
 (3802, 'A', 'C'),
 (3803, 'T', 'G'),
 (3807, 'A', 'C'),
 (3808, 'A', 'C'),
 (3810, 'A', 'C'),
 (3812, 'A', 'C'),
 (3812, 'A', 'T'),
 (3813, 'A', 'C'),
 (3814, 'G', 'C'),
 (3816, 'A', 'C'),
 (3818, 'A', 'C'),
 (3821, 'T', 'C'),
 (3823, 'T', 'G'),
 (3826, 'T', 'G'),
 (3827, 'T', 'G'),
 (3833, 'T', 'G'),
 (3834, 'G', 'T'),
 (3836, 'C', 'A'),
 (3837, 'A', 'C'),
 (3838, 'T', 'A'),
 (3846, 'C', 'A'),
 (3847, 'T', 'G'),
 (3847, 'T', 'A'),
 (3848, 'T', 'G'),
 (3849, 'G', 'T'),
 (3854, 'T', 'G'),
 (3855, 'A', 'T'),
 (3858, 'A', 'C'),
 (3859, 'T', 'G'),
 (3862, 'T', 'C'),
 (3866, 'T', 'A'),
 (3866, 'T', 'G'),
 (3868, 'T', 'G'),
 (3871, 'A', 'C'),
 (3873, 'A', 'C'),
 (3875, 'T', 'G'),
 (3876, 'A', 'C'),
 (3877, 'G', 'T'),
 (3881, 'A', 'T'),
 (3882, 'G', 'C'),
 (3883, 'A', 'T'),
 (3884, 'C', 'A'),
 (3886, 'A', 'T'),
 (3886, 'A', 'C'),
 (3887, 'A', 'C'),
 (3892, 'A', 'G'),
 (3892, 'A', 'C'),
 (3898, 'T', 'A'),
 (3899, 'T', 'C'),
 (3904, 'C', 'A'),
 (3905, 'T', 'G'),
 (3906, 'T', 'C'),
 (3906, 'T', 'G'),
 (3908, 'C', 'G'),
 (3912, 'A', 'C'),
 (3912, 'A', 'T'),
 (3913, 'G', 'T'),
 (3915, 'G', 'C'),
 (3919, 'T', 'G'),
 (3921, 'C', 'T'),
 (3923, 'A', 'T'),
 (3925, 'C', 'G'),
 (3926, 'T', 'G'),
 (3927, 'A', 'C'),
 (3933, 'A', 'T'),
 (3937, 'T', 'G'),
 (3940, 'A', 'C'),
 (3941, 'A', 'C'),
 (3943, 'A', 'C'),
 (3946, 'G', 'A'),
 (3948, 'A', 'T'),
 (3948, 'A', 'C'),
 (3949, 'T', 'G'),
 (3950, 'A', 'T'),
 (3950, 'A', 'C'),
 (3957, 'A', 'C'),
 (3960, 'C', 'A'),
 (3967, 'G', 'A'),
 (3975, 'C', 'T'),
 (3976, 'T', 'G'),
 (3980, 'T', 'G'),
 (3997, 'A', 'T'),
 (4012, 'A', 'C'),
 (4021, 'A', 'T'),
 (4024, 'A', 'C'),
 (4026, 'A', 'C'),
 (4027, 'A', 'C'),
 (4030, 'T', 'G'),
 (4033, 'C', 'T'),
 (4034, 'T', 'G'),
 (4035, 'A', 'T'),
 (4035, 'A', 'G'),
 (4035, 'A', 'C'),
 (4036, 'G', 'T'),
 (4037, 'G', 'T'),
 (4038, 'A', 'T'),
 (4042, 'A', 'C'),
 (4046, 'A', 'C'),
 (4048, 'G', 'T'),
 (4051, 'G', 'A'),
 (4053, 'A', 'T'),
 (4053, 'A', 'C'),
 (4055, 'T', 'A'),
 (4057, 'T', 'A'),
 (4061, 'C', 'A'),
 (4062, 'T', 'A'),
 (4063, 'G', 'T'),
 (4064, 'A', 'T'),
 (4065, 'A', 'T'),
 (4072, 'A', 'C'),
 (4094, 'C', 'G'),
 (4101, 'T', 'A'),
 (4105, 'A', 'C'),
 (4111, 'C', 'T'),
 (4129, 'A', 'G'),
 (4144, 'T', 'G'),
 (4678, 'T', 'G'),
 (4712, 'C', 'A'),
 (4714, 'G', 'T'),
 (4722, 'A', 'C'),
 (4726, 'T', 'G'),
 (4732, 'A', 'T'),
 (4779, 'A', 'C'),
 (4800, 'T', 'C'),
 (4806, 'T', 'G'),
 (4807, 'T', 'C'),
 (4815, 'C', 'A'),
 (4825, 'C', 'A'),
 (4826, 'C', 'A'),
 (4830, 'G', 'T'),
 (4831, 'G', 'T'),
 ...]

In [193]:
((fwd_cell_variant_df >= 2) & (rev_cell_variant_df >= 2)).sum()

34G>T       0
39C>A       0
45A>C       0
46T>G       0
49A>C       0
           ..
16542C>T    0
16543G>T    0
16547C>A    0
16558G>T    0
16561A>C    0
Length: 6231, dtype: int64

In [194]:
heteroplasmic_df

,34G>T,39C>A,45A>C,46T>G,49A>C,51T>A,52T>G,58T>G,65T>G,73A>G,...,16534A>C,16534A>G,16535G>T,16537C>A,16538C>A,16542C>T,16543G>T,16547C>A,16558G>T,16561A>C
AAACCCACAAGAGCTG-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AAACCCACACAGCCAC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACGAACAACGATCT-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AAACGAAGTACCGCGT-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AAACGAATCAATCTCT-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGAGGTGCAACGA-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGGTTAGTGGTCAG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGGTTGTACGAAAT-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGTTGAGCACCAGA-1,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTGTTGAGGCTTCCG-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [195]:
# compute other summary stats
variant_positon = [x[0] for x in variants]
variant_nucleotide = ["{}>{}".format(x[1], x[2]) for x in variants]
variant_n_cells_conf_detected = ((fwd_cell_variant_df >= 2) & (rev_cell_variant_df >= 2)).sum()
variant_n_cells_over_5 = (heteroplasmic_df >= 0.05).sum()
variant_n_cells_over_10 = (heteroplasmic_df >= 0.1).sum()
variant_n_cells_over_20 = (heteroplasmic_df >= 0.2).sum()
variant_n_cells_over_95 = (heteroplasmic_df >= 0.95).sum()
max_heteroplasmy = heteroplasmic_df.max()
variant_mean_coverage = total_coverage_variant_df.mean()

In [196]:
# pack summary stats
variant_output = pd.DataFrame(
    [
        variant_positon,
        variant_nucleotide,
        variant_names,
        variant_vmr,
        variant_mean,
        variant_var,
        variant_n_cells_conf_detected,
        variant_n_cells_over_5,
        variant_n_cells_over_10,
        variant_n_cells_over_20,
        variant_n_cells_over_95,
        max_heteroplasmy,
        variant_strand_corr,
        variant_mean_coverage,
    ]
).T
variant_output.columns = ["position", "nucleotide", "variant", "vmr", "mean", "variance", "n_cells_conf_detected", "n_cells_over_5", "n_cells_over_10", "n_cells_over_20", "n_cells_over_95", "max_heteroplasmy", "strand_correlation", "mean_coverage"]
variant_output[["vmr", "mean", "variance", "strand_correlation", "mean_coverage", "max_heteroplasmy"]] = variant_output[["vmr", "mean", "variance", "strand_correlation", "mean_coverage", "max_heteroplasmy"]].astype(float)

In [197]:
variant_output

,position,nucleotide,variant,vmr,mean,variance,n_cells_conf_detected,n_cells_over_5,n_cells_over_10,n_cells_over_20,n_cells_over_95,max_heteroplasmy,strand_correlation,mean_coverage
0,34,G>T,34G>T,0.721038,0.000871,0.000628,0,2,2,1,0,0.500000,-1.0,1.828025
1,39,C>A,39C>A,0.036336,0.001627,0.000059,0,3,1,0,0,0.111111,-1.0,1.957803
2,45,A>C,45A>C,0.105543,0.001468,0.000155,0,2,1,1,0,0.250000,-1.0,2.168790
3,46,T>G,46T>G,0.080974,0.001420,0.000115,0,4,4,0,0,0.125000,-1.0,2.242834
4,49,A>C,49A>C,0.022477,0.000673,0.000015,0,2,0,0,0,0.062500,-1.0,2.364650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6226,16542,C>T,16542C>T,0.078556,0.001063,0.000083,0,3,2,0,0,0.142857,-1.0,2.247611
6227,16543,G>T,16543G>T,0.025245,0.000715,0.000018,0,1,0,0,0,0.076923,-1.0,2.226911
6228,16547,C>A,16547C>A,0.038654,0.001116,0.000043,0,2,1,0,0,0.111111,-1.0,2.139331
6229,16558,G>T,16558G>T,1.481099,0.001803,0.002670,0,4,4,1,1,1.000000,-1.0,1.766720
6230,16561,A>C,16561A>C,2.216960,0.001475,0.003270,0,2,2,2,1,1.000000,-1.0,1.619427